/*global define*/
define({
    root: {
        ABOUT_DOCDOKUPLM: 'Информация о DocDokuPLM',
        ABSOLUTE: 'Абсолютно',
        ACCEPT_VIDEO_INVITE: 'Принять',
        ACCESS_RIGHTS: 'Приянть правила',
        ACL: 'ACL',
        ACTIVITY_STATE_PLACEHOLDER: 'Новое состояние',
        ADD_ACTIVITY: 'Добавить действие',
        ADD: 'Добваить',
        ADD_CALCULATION: 'Добавить вычисление',
        ADD_COMMENT: 'Добавить комментарий',
        ADD_DOCUMENT: 'Добавить документ',
        ADD_DOCUMENTS_TO_BASELINE: 'Добавить документ в постоянную коллекцию',
        ADD_ISSUE: 'Добавить проблему',
        ADD_NEW_TAG: 'Добавить новый тэг',
        ADD_NOTIFICATION: 'Добавить уведомление',
        ADD_PART: 'Добавить деталь',
        ADD_REQUEST: 'Добавить запрос',
        ADD_REVISION_NOTE: 'Добавить примечание',
        ADD_TASK: 'Добавить задачу',
        ADD_TEMPLATE_ATTRIBUTES: 'Добавить атрибут поставки',
        ADMINISTRATED: 'Администрировать',
        ADVANCED: 'Дополнительно',
        ADVANCED_SEARCH: 'Расширенный поиск',
        AFFECTED_ELEMENT: 'Затрагиваемый элемент',
        ALERT_ROLE_IN_USE: 'Эта роль не может быть удалена, потому что используется в каком-то потоке работ',
        ALL: 'Все',
        ALL_PRODUCTS: 'Все изделия',
        ALL_TASKS: 'Все задачи',
        AMOUNT: 'Количество',
        APPEND: 'Добавить',
        APPEND_LAYER: 'Создать новый слой',
        APPROVE_TASK: 'Пометить задачу как выполненная',
        ASSIGNED_ROLE_PRE_FILL: 'Назначение по умолчанию',
        ASSIGNED_ROLE_REQUIRED: 'Вы должны назначить хотя бы одного пользователя или группу',
        ASSIGNED_USERS: 'Назначенные пользователи',
        ASSIGNED_USERS_PRE_FILL: 'Предварительное заполнение пользователей по умолчанию',
        ASSIGNED_USERGROUPS: 'Назначенные группы',
        ASSIGNED_USERGROUPS_PRE_FILL: 'Предворительное заполнение групп по умолчанию',
        ASSIGNMENTS: 'Назначения',
        ATTACHED_FILES: 'Прикрепленные файлы',
        ATTRIBUTES: 'Атрибуты',
        AUTHOR: 'Автор',
        AUTHOR_LOGIN: 'Логин автора',
        AUTHOR_NAME: 'Имя автора',
        AUTHOR_DOCUMENT_HELP: 'Автор документа или пользователь работавший над этим документом',
        AUTHOR_PART_HELP: 'Автор детали или пользователь работавший над этим деталью',
        AUTO_CHECKIN: 'Автоматически регистрировать детали которые были разрегистрированы во время импорта',
        AUTO_CHECKOUT: 'Автоматически разрегистрировать если необходимо',
        AVG: 'Среднее',
        BACK: 'Назад',
        BASED_ON: 'Основывается на',
        BASELINE: 'Базовая линия',
        BASELINE_DELETION_ERROR: 'Нельзя удалить базовую линию : ',
        BASELINE_OF: 'Базовая линия',
        BASELINES: 'Базовые линии',
        BEST_FIT_VIEW: 'Наилучший вид',
        BLOCKER_TEXT: '(Z, Q, S, D = Перемещение, SPACE = Вверх, CTRL = Вниз, MOUSE = Повернуть вокруг, ESC = Выйти)',
        BLOCKER_TITLE: 'Нажмите чтобы запустить сцену',
        BOM_VIEW: 'Спецификация',
        BOOLEAN: 'Логический',
        BY: 'by',
        CAD_FILE: 'CAD файл',
        CAD_FILES: 'CAD файлы',
        CALCULATIONS: 'Расчеты',
        CALL_TO_TITLE: 'Обратиться к',
        CANCEL: 'Отмена',
        CANCEL_CHECKOUT: 'Отменить разрегистрацию',
        CANCEL_PART_CREATION: 'Отметить создание детали',
        CANNOT_CREATE_PC: 'Невозможно создать объект RTCPeerConnection, WebRTC не поддерживается этим браузером.',
        CANNOT_DELETE_FILE: 'Невозможно удалить файл : ',
        CHANGE_ITEM_ASSIGNEE: 'Назначение',
        CHANGE_ITEM_CATEGORY: 'Категория',
        CHANGE_ITEM_PRIORITY: 'Приоритет',
        CHANGES: 'Редактировать управление',
        CHANGE_MANAGEMENT: 'Редактировать управление',
        CHANNEL_NOT_READY_ERROR: 'Не удается установить связь с сервером вызовов. Пожалуйста, убедитесь, что ваш браузер поддерживает websocket, или ваш интернет-провайдер не блокирует их.',
        CHECK_ALL: 'Проверить все',
        CHECKED_IN: 'Загеристрировано',
        CHECKIN: 'Зарегистрировать',
        CHECKIN_DATE: 'Дата регистрации',
        CHECKOUT_BY: 'Разрегистрировал',
        CHECKOUT: 'Разрегистрировано',
        CHECKOUT_DATE: 'Дата разрегистрации',
        CHECKOUTS: 'Разрегистрировано',
        CHOICES: 'Выбор',
        CHOOSE_A_PRODUCT: 'Выбранный продук',
        CHOSEN_OPTIONALS: 'Исключенный опции',
        CHOSEN_SUBSTITUTES: 'Выбранные заменители',
        CLEAR: 'Очистить',
        CLIPPING: 'Обрезка',
        CLOSE: 'Закрыть',
        CLOSING_PEER_CON: 'Закрытие подключение ...',
        CLOSURE_COMMENT: 'Закрыть комментарий',
        COLLABORATIVE: 'Общий доступ',
        COLLABORATIVE_INVITE: 'Вас приглашают присоединиться к комнате',
        COLLABORATIVE_KICKED: 'Вы были выкинуты из комнаты',
        COLLABORATIVE_LEAD: 'Ведущий',
        COLLABORATIVE_NO_MASTER: 'Отсутствует',
        COLLABORATIVE_NOT_INVITED: 'Вы не приглашены в эту комнату',
        COLLABORATIVE_WITHDRAW_INVITATION: 'Приглашение отменено',
        COMMENT: 'Комментарий',
        COMPONENT_SELECTED: 'Выделенная деталь',
        CONFIG_SPEC: 'Конфигурировать спецификацию',
        CONFIGURATION: 'Конфигурация',
        CONFIGURATIONS: 'Конфигурации',
        CONFIRM: 'Подтвердить',
        CONFIRM_IMPORT: 'Подтвердить импорт?',
        CONFIRM_IMPORT_WITH_OPTION: 'Подтвердить импорт с опциями:',
        CONFIRM_PASSWORD: 'Подтвердить пароль',
        CONNECTED: 'Подключено',
        CONNECTING: 'Подключение...',
        CONTAINS_OBSOLETE_PARTS: 'Содержит устаревшие детали',
        CONTENT: 'Содержание',
        CONTENT_HELP: 'Содержание файла(ов)',
        CONTROLS_SHORTCUTS: 'Горяие клавишы мыши/клавиатуры',
        CONVERSION: 'Преобразование',
        CONVERSION_STATUS: 'Изменение статуса',
        CONVERSION_PENDING: 'Ожидание перехода',
        CONVERSION_SUCCEED: 'Переход успешный',
        CONVERSION_FAILED: 'Переход не удался',
        COPY: 'Копировать',
        COWORKERS: 'Сотрудники',
        CREATE: 'Создать',
        CREATE_BASELINE: 'Создать базовую линию',
        CREATE_DOCUMENT_COLLECTION: 'Создание коллекции документов',
        CREATE_NEW_EFFECTIVITY: 'Создать новую применяемость',
        CREATE_NEW_EFFECTIVITY_ERROR: 'Применяемость не создана',
        CREATE_NEW_EFFECTIVITY_SUCCESS: 'Применяемость создана',
        CREATE_NEW_PART: 'Создать новую деталь',
        CREATE_NEW_PART_AS_SUBSTITUTE: 'Создать новую деталь как замену',
        CREATE_NEW_VERSION: 'Создать новую версию',
        CREATE_PART: 'Создать деталь',
        CREATE_PART_SUBSTITUTE_TOOLTIP: 'Чтобы создать заменяющую ссылку, сначала необходимо выбрать для чего создается ссылка',
        CREATE_PART_TOOLTIP: 'Чтобы создать новую ссылку использования, не один из элементов не должен быть выбран',
        CREATE_PRODUCT: 'Создать изделие',
        CREATE_ROOM: 'Начать обзор цифрового макета',
        CREATION_DATE: 'Дата создания',
        CREATION_ERROR: 'Произошла ошибка во время создания',
        CURRENT_TAGS: 'Теги связанные с',
        CURRENT_WORKFLOW: 'Текущий поток работ',
        CUTPLAN: 'План разреза',
        DATE: 'Дата',
        _DATE_FORMAT: 'MM-DD-YYYY HH:mm:ss',
        _DATE_PICKER_DATE_FORMAT: 'YYYY-MM-DD',
        _DATE_SHORT_FORMAT: 'MM-DD-YYYY',
        DATE_SORT: 'date_sort',
        DBL_CLICK: 'Двойной клик',
        DELETE_ACTIVITY: 'Удалить действие',
        DELETE: 'Удалить',
        DELETE_FOLDER_QUESTION: 'Удалить папку?',
        DELETE_LINKED_ITEM: 'Удалить ссылку',
        DELETE_MARKER: 'Удалить маркер',
        DELETE_PRODUCT_CONFIRM: 'Вы действительно хотите удалить это изделие?',
        DELETE_PRODUCT: 'Удалить изелие',
        DELETE_PRODUCT_ERROR: 'Ошибка при удаление изделия',
        DELETE_SELECTION: 'Удалить выбранное',
        DELETE_SELECTION_QUESTION: 'Удалить выбранное',
        DELETE_TAG_QUESTION: 'Удалить выбранный тег?',
        DELETE_QUERY_QUESTION: 'Удалить выбранный запрос?',
        DELETE_TASK: 'Удалить задачу',
        DESCRIPTION: 'Описание',
        DEVICE_ERROR: 'Невозможно получить доступ к вашему аудио/видео устройству, пожалуйста, выберите браузер поддерживащий WebRTC, и если на этом веб-сайте нет исключения.',
        DISPLAY_COMMENTS: 'Скрыть/показать определение',
        DOCUMENT: 'Документ',
        DOCUMENT_REVISION_NOTE_PROMPT_LABEL: 'Вы хотите добавить примечание к документу без него?',
        DOCUMENT_S_DESCRIPTION: 'Описание документа',
        DOCUMENT_S_REFERENCE: 'ID документа',
        DOCUMENT_S_TITLE: 'Заголовок документа',
        DOCUMENT_TEMPLATES: 'Шаблон документа',
        DOCUMENT_TYPE_HELP: 'Тип документа',
        DOCUMENT_VERSION_HELP: 'Версия документа',
        DOCUMENTS: 'Документы',
        DOCUMENTS_CHOICE: 'Выбранные документы',
        DOCUMENTS_CHOICE_EXPLANATION: 'Выберите несколько документы из папки',
        DOCUMENT_COLLECTION: 'Колекция документов',
        DOCUMENT_COLLECTION_IN_PROGRESS: 'Колекция документов в процессе',
        DOCUMENT_COLLECTIONS: 'Колекции документов',
        DOCUMENT_MANAGEMENT: 'Управление документами',
        DOWNLOAD_DPLM_CLIENT: 'Скачать DPLM клиент',
        DOWNLOAD_ZIP: 'Скачать все файлы в ZIP',
        DROP_FILE_HERE: 'или удалить его здесь',
        DROP_FILES_HERE: 'или удалить их здесь',
        DUE_DATE: 'срок',
        DUPLICATE: 'Дубликат',
        DUPLICATE_WORKFLOW: 'Дублировать поток работ',
        EDIT_BASELINE: 'Редактировать базовую линию',
        EDIT: 'Редактировать',
        EDIT_ISSUE: 'Редактировать ошибку',
        EDIT_LINKED_DOCUMENTS: 'Редактировать ссылку',
        EDIT_MILESTONE: 'Редактировать веху',
        EDIT_ORDER: 'Редактировать заказ',
        EDIT_PRODUCT: 'Редактировать изделие',
        EDIT_PRODUCT_INSTANCE: 'Редактировать доставку',
        EDIT_REQUEST: 'Редактировать запрос',
        EDITION_ERROR: 'Произошла ошибка во время редактирования',
        EFFECTIVITY: 'Применяемость',
        EFFECTIVITY_DATE: 'Дата',
        EFFECTIVITY_DESCRIPTION: 'Описание',
        EFFECTIVITY_END_DATE: 'Дата окончания',
        EFFECTIVITY_END_LOT_ID: 'Конечная партия',
        EFFECTIVITY_END_NUMBER: 'Конец серийного номера',
        EFFECTIVITY_LOT: 'Базовая партия',
        EFFECTIVITY_NAME: 'Название',
        EFFECTIVITY_SERIAL_NUMBER: 'Базовый серийный номер',
        EFFECTIVITY_START_DATE: 'Дата начала',
        EFFECTIVITY_START_LOT_ID: 'Начальная партия',
        EFFECTIVITY_START_NUMBER: 'Начало серийного номера',
        EFFECTIVITY_TYPE: 'Тип применяемости',
        EMBED_SCENE: 'Вставить сцены',
        EMAIL: 'Email',
        EMPTY_CHOICES: 'Нельзя создать конфигурацию без выбранной детали',
        EMPTY_REVISION_NOTE: 'Пустое примечание. Пожалуйста, отключите опцию или напишите примечание',
        END: 'Конец',
        ENTER_NAV: 'Начать навигацию',
        ERROR: 'Ошибка',
        ERRORS: 'Ошибки:',
        ERROR_404: 'ERROR 404. Мы не смогли найти то, что вы ищете...',
        ERROR_404_SORRY: 'Извините !',
        EXISTING_TAGS: 'Доступные теги',
        EXIT: 'Закончить обзор цифрового макет',
        EXPIRE_DATE: 'Срок годности',
        EXPLODE: 'Развернуть',
        EXPORT: 'Экспорт',
        EVERYTHING: 'Все',
        FALSE: 'Ложь',
        FILE: 'Файл',
        FILE_DELETION_ERROR: 'Файл с %{id} не может быть удален',
        FILE_UPLOADED: 'Файл загружен',
        FILES_UPLOADED: 'Файлы загружены',
        FILES: 'Файлы',
        FILL: 'Заполнить',
        FILTER: 'Филтр',
        FINAL_STATE_PLACEHOLDER: 'Конечное состояние',
        FIRST_PAGE: 'Первая страница',
        FIT_VIEW: 'Подходящий вид',
        FLYING_MODE: 'Порящая модель',
        FLY_TO: 'Переместиться в',
        FOLDER: 'Папка',
        FOLDERS: 'Папки',
        FOLDER_S_NAME: 'Имя папки',
        FOLD_TASK: 'Минимизировать задачи',
        FORBIDDEN: 'Доступ запрещен',
        FORBIDDEN_MESSAGE: 'Вы не можете получить доступ к этому ресурсу, вам необходимо войти в систему',
        FORM_HELPER: 'Оставьте эти поля пустыми, если вы не хотите указывать пароль или дату истечения срока действия',
        FREEZE_CURRENT_ITERATION: 'Блокировать текущую итерацию',
        FREEZE_AFTER_MODIFICATION: 'Блокировать итерацию после изменения',
        FROM: 'Из',
        FULL_ACCESS: 'Полный доступ',
        FULL_SCREEN: 'Полный экран',
        GENERAL: 'Основной',
        GENERATED_URL: 'Сгенерированный URL',
        GIVE_HAND: 'Помочь',
        GO_TO_PAGE: 'Перейти к странице ...',
        GOTO_PARALLEL_MODE: 'Переключить действие в параллельный режим',
        GOTO_SEQUENTIAL_MODE: 'Переключить действие в последовательный режим',
        GRID_SWITCH: 'Показать/скрыть сетку',
        GROUPS: 'Группы',
        HAS_SUBSTITUTES: 'Имеет заменитель',
        HEAD_CHECKIN: 'Последняя регистрация',
        HEAD_RELEASED: 'Последний релиз',
        HEAD_WIP: 'В работе',
        HIDE_SUBSTITUTES: 'Скрыть заменитель',
        HOME_PAGE: 'Домой',
        HOURS: 'ч',
        HISTORY: 'История',
        ID_GENERATION: 'Id генератор',
        IGNORE: 'Игнорировать',
        IMPORT_ATTRIBUTE_FILE: 'Импорат атрибутов файла',
        IMPORT_DELIVERABLE_DATA: 'Импорт данных доставки',
        IMPORT_PART_DATA: 'Ипорт данных детали',
        IMPORTER: 'Импорт',
        IMPORT_PENDING: 'Идет импорт',
        IMPORT_SUCCEED: 'Успешно импортировано',
        IMPORT_FAILED: 'Импорт не удался',
        INIT_VALUE: 'Начальная значение',
        IN_PROGRESS: 'В работе',
        INITIATOR: 'Инициатор',
        INSTANCE_SELECTED: 'Выбран экземпляр',
        INSTRUCTIONS: 'Инструкции',
        INVERT_SOURCE_DESTINATION: 'Поменять местами отправление и назначение',
        INVITE: 'Пригласите колег',
        ISSUES: 'Ошибки',
        IS_COMPONENT_OF: 'Является компонентом :',
        IS_SUBSTITUTE_IN: 'Поставляется в :',
        IS_SUBSTITUTE: 'Замена',
        ITERATION_CHANGE: 'Изменение итерации',
        ITERATION: 'Итерация',
        KEYBOARD_SHORTCUTS: 'Горячие клавиши',
        KG: 'кг',
        LAST_ITERATION: 'Текущая итерация',
        LAST_PAGE: 'Последняя страница',
        LATEST: 'Последний(яя)',
        LATEST_SHORT: 'Последняя версия',
        LAYERS: 'Слои',
        LEAVE_NAV: 'Остановить навигацию',
        LEFT_CLICK: 'Левая клавиша мишы',
        LIFECYCLE_STATE: 'Состояние жизненного цикла',
        LINK_DESCRIPTION: 'Ссылка на описание',
        LINKED_DOCUMENTS: 'Ссылающиеся документы',
        LINKS: 'Ссылки',
        LOADING: 'Загрузка',
        LOCK_ATTRIBUTES: 'Зафиксировать структуру атрибутов',
        LOCKED: 'Заблокировано',
        LOGIN: 'Войти',
        LOGOUT: 'Выйти',
        LOOK_AT: 'Посмотреть на',
        MANAGE_PRODUCT: 'Управление изделиями',
        MANAGE_ROLES: 'Административные роли',
        MANDATORY: 'Обязательное',
        MARK_ALL_AS_VERIFIED: 'Отметить все как проверенные',
        MARK_AS_VERIFIED: 'Отметить как проверенно',
        MARK_AS_OBSOLETE: 'Отметить как устаревшее',
        MARK_DOCUMENT_AS_OBSOLETE_QUESTION: 'Отметить как устаревшее выделнный документ?',
        MARK_PART_AS_OBSOLETE_QUESTION: 'Отметить как устаревшее выделенную деталь?',
        MARKER_INFO: 'Получить информацию о маркерах',
        MARKERS: 'Маркеры',
        MARKERS_OPACITY: 'Изменить прозрачность маркеров',
        MARKERS_SIZE_MAX: 'Увеличить размер маркеров',
        MARKERS_SIZE_MIN: 'Уменьшить размер маркеров',
        MASK_HELP: 'Определите формат маски для ID документов/деталей, в которых будет подставляться этот шаблон. \n\nКроме того, для любых обычных символов вы можете использовать \'#\' для любого допустимого числа и \'*\' для любого символа. \n\nДля ID \'FAX-AZE-12\' можно использовать следующюю маску \'FAX-***-##\'.\n\n Маска с любым символом подстановочных знаков не может быть использована более одного раза.',
        MASK: 'Маска',
        MEASURE: 'Размер',
        METER: 'м',
        MILESTONE: 'Веха',
        MILESTONES: 'Вехи',
        MODIFICATION_DATE: 'Изменная дата',
        MODIFICATION_NOTIFICATION_LIST_DESCRIPTION: 'История изменений подсборок/деталей',
        MOUSE_CONTROLS: 'Управление мышью',
        MOVE: 'переместить',
        MOVE_BACKWARD: 'Назад',
        MOVE_DOWN: 'Вниз',
        MOVE_FORWARD: 'Вперед',
        MOVE_LEFT: 'Влево',
        MOVE_RIGHT: 'Вправо',
        MOVE_SCENE: 'Переместиться в сцену',
        MOVE_UP: 'Вверх',
        MULTIPLE_VERSIONS_FOR_DOCUMENT: 'Этот документ уже добавлен с другой версией',
        MY_ACCOUNT: 'Мой профиль',
        MY_ORGANIZATION: 'Моя организация',
        MY_WORKSPACES: 'Мое рабочее пространство',
        NAME: 'Имя',
        NAVIGATION: 'Навигация',
        NB_TASKS_TO_COMPLETE: 'Задача завершена',
        NEW_BASELINE: 'Новая базовая линия',
        NEW_CONFIGURATION: 'Новая конфигурация',
        NEW_DOCUMENT: 'Новый документ',
        NEW_DOCUMENT_COLLECTION: 'Новая колекция документа',
        NEW_EFFECTIVITY: 'Новая применяемость',
        NEW_FOLDER: 'Новая папка',
        NEW_ISSUE: 'Новая проблема',
        NEW_LAYER: 'Новый слой',
        NEW_LINK_TYPE: 'Создать новый тип ссылки',
        NEW_MARKER: 'Новый маркер',
        NEW_MILESTONE: 'Новая веха',
        NEW_ORDER: 'Новый заказ',
        NEW_PART: 'Новая деталь',
        NEW_PART_TEMPLATE: 'Новый шаблон детали',
        NEW_PRODUCT_INSTANCE: 'Новая доставка',
        NEW_PRODUCT: 'Новое изделие',
        NEW_REQUEST: 'Новый запрос',
        NEW_ROLE: 'Новая роль',
        NEW_TAG: 'Новый тег',
        NEW_TEMPLATE: 'Новый шаблон документа',
        NEW_UNIT: 'Новая единица',
        NEW_VERSION: 'новая версия',
        NEW_VERSION_OF: 'новая версия',
        NEW_WORKFLOW: 'Новый поток работ',
        NEXT_PAGE: 'Next Следующая страница',
        NO_CONVERSION: 'Нет изменений',
        NO_COWORKER: 'Нет колег',
        NO_DATA: 'Данные отсутствуют в таблице',
        NO_FILE_TO_IMPORT: 'Файл не импортирован',
        NO_FILTERED_DATA: 'Подходящих записей не найдено',
        NO_LAYERS: 'Нет слоев',
        NO_PARTICIPANT: 'Нет участников. Пригласите участника из меню Коллеги',
        NOTIFICATIONS: 'Уведомление',
        NOTHING_HERE: 'Ничего не найдно. Не верная ссылка...',
        NOT_INVITED_COLLABORATIVE_ROOM: 'У вас нет приглашения к этой комнате',
        NOT_VERIFIED: 'Не проверено',
        NO_WEBGL: 'Нет доступного или активного WebGL',
        NOT_YET_REGISTERED_QUESTION: 'Вы не зарегистрированы?',
        NOT_YET_REGISTERED_REGISTER: 'Зарегистрироваться!',
        NODE_ASSEMBLIES_VISITED: 'Посещаемые собрания',
        NODE_INSTANCES_VISITED: 'Посещаемые объекты',
        NONE: 'Ничего',
        NOTIFY_BY_TAG: 'Уведомить пользователя(ей) об изменениях помечаных тегом...',
        NUMBER: 'Число',
        LITER: 'л',
        LIST_LOV: 'Редактировать списки значений',
        LOCK: 'Заблокировать',
        LOV: 'Лист значений',
        OBSOLETE: 'Устаревший',
        OBSOLETE_AUTHOR: 'Устаревший автора',
        OBSOLETE_DATE: 'Устаревшая дата',
        OFFICIAL_SITE: 'Сообщество PLM',
        OFFLINE: 'Оффлайн',
        OK: 'OK',
        ON: 'нет',
        OR: 'или',
        ONLINE: 'Онлайн',
        OPEN_NEW_WINDOW: 'Открыть в новом окне',
        OPTIONAL: 'Опционально',
        OPTIONAL_REMOVE: 'None',
        OPTIONS: 'Опции',
        OR_ADD_PART: 'Или добавить сущствующую деталь',
        ORBIT_MODE: 'Режим Orbit',
        ORDERS_NUMBER: 'Число заказов',
        ORDERS: 'Заказы',
        OTHERS: 'Остальные',
        PATH_TO_PATH_LINKS: 'Типизированные ссылки',
        PARALLEL_ACTIVITY: 'Требуется паралельная ',
        PART_ATTRIBUTES: 'Атрибуты детали',
        PART_ATTRIBUTES_TEMPLATES: 'Шаблоны атрибутов детали',
        PARTICIPANT: 'Участники',
        PART_DESCRIPTION: 'Описание',
        PART_NAME: 'Название',
        PART_NOT_FOUND: 'Родительская деталь не найдена',
        PART_NUMBER_HELP: 'Номер детали',
        PART_NUMBER: 'Номер детали',
        PARTS: 'Детали',
        PART_REVISION_NOTE_PROMPT_LABEL: 'Добавить примечание к детали без нее?',
        PART_SEARCH_HELP: 'Текст',
        PART_SUBSTITUTE: 'Деталь аналог',
        PARTS_SUBSTITUTES: 'Детали аналоги',
        PART_TEMPLATE: 'Шаблон детали',
        PART_TEMPLATES: 'Шаблоны',
        PART_TYPE_HELP: 'Тип детали',
        PART_VERSION_HELP: 'Версия детали',
        PASSWORD_NOT_CONFIRMED: 'Введенные пароли должны совпадать',
        PASSWORD: 'Пароль',
        PATH: 'Папка',
        PATH_TO_PATH_SOURCE: 'Из этой папки',
        PATH_TO_PATH_TARGET: 'В эту папку',
        PATH_TO_PATH_SOURCE_LINK: 'Ссылка на исходную папку',
        PATH_TO_PATH_TARGET_LINK: 'Ссылка на целевую папку',
        PENDING: 'Отсутствующий участник',
        PERMALINK: 'Постоянная ссылка',
        PERMISSIVE_UPDATE_PART: 'Обновление по разрешению (обновляются только изменные детали)',
        PERMISSIVE_UPDATE_PATH_DATA: 'Обновление по разрешению (обновляются только изменные данные о поставках)',
        POSSIBLE_VALUE: 'возможные значения',
        PREVIOUS_PAGE: 'Предыдущая страция',
        PRIVATE_SHARE_TITLE: 'Папка с ограниченным доступом',
        PRODUCT: 'Изделие',
        PRODUCT_ID: 'Id Изделия',
        PRODUCT_INSTANCE: 'Изделие для доставки',
        PRODUCT_INSTANCES: 'Изделия для доставки',
        PRODUCT_INSTANCE_DATA: 'Дата доставки изделия',
        PRODUCT_INSTANCE_DATA_ATTRIBUTES: 'Данные атрибутов для доставки изделия',
        PRODUCT_INSTANCE_DATA_ATTRIBUTES_TEMPLATES: 'Шаблон для данных атрибутов доставки изделия',
        PRODUCT_NAME: 'Название',
        PRODUCT_MANAGEMENT: 'Управление изделиями',
        PRODUCTS: 'Изделия',
        PRODUCT_STRUCTURE: 'Структура изделия',
        PROTECTED_RESOURCE: 'Этот ресурс защищен паролем',
        PUBLIC_ACCESS_TITLE: 'Отркытый доступ по постоянной ссылке',
        PUBLIC_SHARE: 'Папка с общим доступом',
        PUBLISH: 'Опубликовать',
        QUERY_EXPORT_EXCEL_LOADING: 'Экспорт...',
        QUERY_EXPORT_EXCEL: 'Экспорт из Excel',
        QUICK_SEARCH: 'Быстрый поиск',
        QUERY_STANDARD: 'Стандартный запрос',
        QUERY_BUILDER_CONDITION_AND: 'И',
        QUERY_BUILDER_CONDITION_OR: 'ИЛИ',
        QUERY_BUILDER_OPERATORS_EQUALS: 'равен',
        QUERY_BUILDER_OPERATORS_NOT_EQUALS: 'не равен',
        QUERY_BUILDER_OPERATORS_IN: 'содержится в',
        QUERY_BUILDER_OPERATORS_NOT_IN: 'не содержится в',
        QUERY_BUILDER_OPERATORS_LESS: 'меньше',
        QUERY_BUILDER_OPERATORS_LESS_OR_EQUAL: 'меньше или равно',
        QUERY_BUILDER_OPERATORS_GREATER: 'больше',
        QUERY_BUILDER_OPERATORS_GREATER_OR_EQUAL: 'больше или равно',
        QUERY_BUILDER_OPERATORS_BETWEEN: 'между',
        QUERY_BUILDER_OPERATORS_BEGIN_WITH: 'начинается с',
        QUERY_BUILDER_OPERATORS_NOT_BEGIN_WITH: 'не начинается с',
        QUERY_BUILDER_OPERATORS_CONTAINS: 'содержит',
        QUERY_BUILDER_OPERATORS_NOT_CONTAINS: 'не содержит',
        QUERY_BUILDER_OPERATORS_ENDS_WITH: 'оканчивается на',
        QUERY_BUILDER_OPERATORS_NOT_ENDS_WITH: 'не оканчивается на',
        QUERY_BUILDER_OPERATORS_IS_EMPTY: 'ПУСТОЕ',
        QUERY_BUILDER_OPERATORS_IS_NOT_EMPTY: 'НЕ ПУСТОЕ',
        QUERY_BUILDER_OPERATORS_IS_NULL: 'NULL',
        QUERY_BUILDER_OPERATORS_IS_NOT_NULL: 'не NULL',
        QUERY_BUILDER_ERRORS_NO_FILTER: 'Не выбран фильтр',
        QUERY_BUILDER_ERRORS_EMPTY_GROUP: 'Группа пустая',
        QUERY_BUILDER_ERRORS_RADIO_EMPTY: 'Не выбрано значение',
        QUERY_BUILDER_ERRORS_CHECKBOX_EMPTY: 'Не выбрано значение',
        QUERY_BUILDER_ERRORS_SELECT_EMPTY: 'Не выбрано значение',
        QUERY_BUILDER_ERRORS_STRING_EMPTY: 'Пустое значение',
        QUERY_BUILDER_ERRORS_STRING_EXCEED_MIN_LENGTH: 'Должен содержать не менее {0} символов',
        QUERY_BUILDER_ERRORS_STRING_EXCEED_MAX_LENGTH: 'Долже содержать более {0} символов',
        QUERY_BUILDER_ERRORS_STRING_INVALID_FORMAT: 'Неверный формат ({0})',
        QUERY_BUILDER_ERRORS_NUMBER_NAN: 'Не число',
        QUERY_BUILDER_ERRORS_NUMBER_NOT_INTEGER: 'Не целое число',
        QUERY_BUILDER_ERRORS_NUMBER_NOT_DOUBLE: 'Не дробное число',
        QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MIN: 'Должно быть больше чем {0}',
        QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MAX: 'Должно быть меньше чем{0}',
        QUERY_BUILDER_ERRORS_NUMBER_WRONG_STEP: 'Должно быть кратным {0}',
        QUERY_BUILDER_ERRORS_DATETIME_EMPTY: 'Пустое значение',
        QUERY_BUILDER_ERRORS_DATETIME_INVALID: 'Неверный формат даты ({0})',
        QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MIN: 'Должно быть после {0}',
        QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MAX: 'Должно быть перед {0}',
        QUERY_BUILDER_ERRORS_BOOLEAN_NOT_VALID: 'Не логическое',
        QUERY_BUILDER_ERRORS_OPERATOR_NOT_MULTIPLE: 'Оператор {0} не может принимать несколько значений',
        QUERY_GROUP_AUTHOR: 'Автор',
        QUERY_GROUP_PART_MASTER: 'Мастер деталь',
        QUERY_GROUP_PART_REVISION: 'Пересмотр детали',
        QUERY_GROUP_PRODUCT: 'Изделие',
        QUERY_GROUP_ATTRIBUTE_STRING: 'Строковый атрибут',
        QUERY_GROUP_ATTRIBUTE_LONG_STRING: 'Атрибут длинная строка',
        QUERY_GROUP_ATTRIBUTE_PART_NUMBER: 'Атрибут номер детали',
        QUERY_GROUP_ATTRIBUTE_LOV: 'Атрибут список значений',
        QUERY_GROUP_ATTRIBUTE_URL: 'Атрибут URL',
        QUERY_GROUP_ATTRIBUTE_NUMBER: 'Числовый атрибут',
        QUERY_GROUP_ATTRIBUTE_DATE: 'Атрибут дата',
        QUERY_GROUP_ATTRIBUTE_BOOLEAN: 'Логический атрибут',
        QUERY_GROUP_CONTEXT: 'Контекст',
        QUERY_GROUP_PATH_DATA_ATTRIBUTE: 'Атрибут доставки',
        QUERY_NAME: 'Имя запроса',
        QUERY_SEARCH: 'Построитель запросов',
        QUERY_SELECT: 'Выбрать',
        QUERY_CONTEXT: 'Конекст',
        QUERY_WHERE: 'Где',
        QUERY_WHERE_CONTEXT: 'Фильтр поставляемых данных',
        QUERY_ORDER_BY: 'Сортировать по',
        QUERY_GROUP_BY: 'Группировать по',
        QUERY_CLEAR: 'очистить',
        QUERY_REMOVE_SAVED_QUERY: 'Удалить из списка запросов',
        QUERY_CHOOSE_EXISTING_REQUEST: 'Или используйте существующий...',
        QUERY_CONTEXT_ERROR: 'Не удается найти изделия',
        QUERY_ATTRIBUTES_ERROR: 'Не удается получить список атрибутов',
        QUERY_FILTER_STATUS_WIP: 'В работе',
        QUERY_FILTER_STATUS_RELEASED: 'Выпущено',
        QUERY_FILTER_STATUS_OBSOLETE: 'Устарело',
        QUERY_DEPTH: 'Глубина',
        READ_ONLY: 'Read only',
        REBASE: 'Rebase',
        REBASE_AUTHOR: 'Rebase author',
        REBASE_SUCCESS: 'The deliverable has been rebased',
        REFERENCE_HELP: 'Document ID',
        REFERENCE: 'ID',
        REFRESH_TREE: 'Refresh tree',
        REJECT_TASK: 'Reject task',
        REJECT_VIDEO_INVITE: 'Reject',
        RELATIVE: 'Relative',
        RELAUCNH_ACTIVITY_SELECTOR: 'Relaunch activity if rejected',
        RELEASE_DATE: 'Release date',
        RELEASED_BY: 'Released by',
        RELEASED: 'Released',
        RELEASED_SHORT: 'Latest released versions',
        RELEASE: 'Release',
        RELEASE_NOW: 'Release now',
        RELEASE_SELECTION_QUESTION: 'Release selection?',
        RELOAD: 'Reload',
        REMOTE_ACCEPT: 'Remote user has accepted the call. Waiting for connection ...',
        REMOTE_BUSY: 'Remote user is busy. Call aborted ...',
        REMOTE_HANGUP: 'Remote user hang up',
        REMOTE_OFFLINE: 'Remote user is offline. Call ended ...',
        REMOTE_REJECT: 'Remote user has rejected the call. Call ended ...',
        REMOTE_STEAM_ADDED: 'Remote stream added',
        REMOTE_STEAM_REMOVED: 'Remote stream removed',
        REMOTE_TIMEOUT: 'Remote user didn\'t answer in time. Call aborted ...',
        REMOVE_DOCUMENT_FROM_COLLECTION: 'Remove document from collection',
        RENAME: 'Rename',
        RENAME_WORKFLOW_COPY: 'Name of the copy',
        REPLACE: 'Reset',
        REQUESTS_NUMBER: 'Number of request',
        REQUESTS: 'Requests',
        REQUIRED_FIELD: 'Please fill out this field',
        RESET: 'Reset',
        RESET_CAMERA: 'Reset camera',
        RESULT: 'Result',
        RETAIN: 'Retain',
        RETRY: 'Retry',
        REVISION_DATE: 'Revision date',
        REVISION_NOTE: 'Revision note',
        REVISION_NOTE_PROMPT_CANCEL: 'Ignore',
        REVISION_NOTE_PROMPT_LABEL: 'Do you want to add a revision note?',
        REVISION_NOTE_PROMPT_OK: 'Add revision note',
        RIGHT_CLICK: 'right click',
        ROLE_NAME: 'Role name',
        ROLE: 'Role',
        ROLES: 'Roles',
        ROOT_PART: 'Root part',
        ROTATE: 'Rotate',
        ROTATE_SCENE: 'Rotate the scene',
        RUN: 'Run',
        SAVED: 'Saved',
        SAVE: 'Save',
        SCALE: 'Scale',
        SCENE_VIEW: 'Scene view',
        SCROLL_DOWN: 'scroll down',
        SCROLL_UP: 'scroll up',
        SEARCH_OPTIONS: 'Search options by number or name',
        SEARCH_PART_BEGINNING: 'Search part beginning by',
        SEARCH_PART_CALLED: 'Search part called',
        SEARCH_PART_ENDING: 'Search part ending by ',
        SEARCH_PARTS: 'Search parts',
        SEARCH: 'Search',
        SEARCHING: 'Searching...',
        SEARCHING_FOR_PARTS: 'Searching for parts, please do not close the window...',
        SECONDS: 's',
        SEE_IN_DOCUMENT_MANAGEMENT: 'See the document in the document management module',
        SEE_IN_PRODUCT_MANAGEMENT: 'See the part in the product management module',
        SELECT_FILE: 'Choose a file',
        SELECT_FILES: 'Choose one or more file(s)',
        SEND: 'Send',
        SEQUENTIAL_ACTIVITY: 'In sequential',
        SERIAL_NUMBER: 'Serial number',
        SESSION_CONNECTING: 'Session connecting',
        SESSION_OPENED: 'Session opened',
        SERVER_NOT_AVAILABLE: 'Server isn\'t available, please try again',
        SHARED_DOCUMENTS_TITLE: 'Share document',
        SHARED_PARTS_TITLE: 'Share part',
        SHARE: 'Share',
        SHORTCUTS_TITLE: 'Keyboard / mouse shortcuts',
        SHOW_ALL: 'Show all',
        SHOW_BY_PAGE: 'Show by page',
        SHOW_EDITED_MESHES: 'Highlight edited meshes',
        SHOW_SUBSTITUTES: 'Show substitutes',
        SIGN_TASK: 'Signing up',
        SINGLE_FILE_RESTRICTION: 'Only one file is allowed',
        SORRY: 'Sorry',
        SPACE: 'space',
        SQUARE_METER: 'm²',
        STANDARD_PART_ALL: 'All',
        STANDARD_PART_FALSE: 'No',
        STANDARD_PART: 'Standard part',
        STANDARD_PART_TRUE: 'Yes',
        START: 'Start',
        START_IMPORT: 'Start import',
        STATE_CHANGE: 'State change',
        STATUS: 'Status',
        STRUCTURE: 'Structure',
        SUB_PARTS: 'Assembly',
        SUM: 'Sum',
        SUBSCRIBE_ITERATION_CHANGE: 'Subscribe to iteration change notifications',
        SUBSCRIBE_STATE_CHANGE: 'Subscribe to document state change notifications',
        TAG: 'Tag',
        TAGS_HELP: 'Tags list, comma separated',
        TAGS: 'Tags',
        TAGS_TO_ADD: 'Tags to add',
        TAKE_SCREENSHOT: 'Take screenshot',
        TASK_APPROVED_ON: 'Task done on',
        TASK_CLOSED_ON: 'Task closed on',
        TASK_NAME_PLACEHOLDER: 'New task',
        TASK_REJECT_ON: 'Task reject on',
        TASK_WORKER: 'Processed by',
        TASKS_IN_PROGRESS: 'In progress',
        TASKS: 'Tasks',
        TEMPLATES: 'Templates',
        TEMPLATE: 'Template',
        TEXT: 'Text',
        LONG_TEXT: 'Long text',
        TITLE_HELP: 'Document title',
        TITLE: 'Title',
        TO: 'To',
        TOGGLE_ALL_LAYERS: 'Toggle all layers',
        TRACKBALL_MODE: 'Trackball mode',
        TRANSFORM_CONTROLS: 'Transformation',
        TRUE: 'True',
        TYPE: 'Type',
        UDF_DEF: 'Define function',
        UNCHECK_ALL: 'Uncheck all',
        UNDO_CHECKOUT: 'Cancel checkout',
        UNDO_CHECKOUT_QUESTION: 'Undo checkout?',
        UNFOLD_TASK: 'Edit task',
        UNREACHABLE: 'Cannot invite user, user is unreachable',
        UNSUBSCRIBE_ITERATION_CHANGE: 'Unsubscribe from iteration change notifications',
        UNSUBSCRIBE_STATE_CHANGE: 'Unsubscribe from document state change notifications',
        UNIT: 'each',
        UNEXPECTED_ERROR: 'An unexpected error happened, please try again or contact support',
        UPDATE_ACL_ERROR: 'An error occurred while updating acl',
        URL: 'URL',
        USE_ACL: 'Use ACL ?',
        USER_DEFINED_FUNCTION: 'User defined function',
        USER_MEDIA_FAILED: 'Cannot access to your video input. Is this a WebRTC capable browser?',
        USERS_CONNECTED: 'users connected',
        USERS: 'Users',
        VALIDATION_FAILED_FOR: 'Validation failed for ',
        _VALIDATION_PATTERN_DATE: '\\d{4}-\\d{2}-\\d{2}',
        _VALIDATION_PATTERN_NUMBER: '^-?\\d+(\\.\\d+)?(([eE]([-+])?)?\\d+)?$',
        _VALIDATION_PATTERN_TIME: '\\d{2}:\\d{2}',
        VALUE: 'Value',
        VALUES: 'Values',
        VERIFICATION_NOTE: 'Verification note',
        VERIFIED: 'Verified',
        VERSION: 'Version',
        VERSIONS: 'Versions',
        VIDEO_INVITATION_SENT: 'Invitation has been sent to remote user, waiting for him/her to accept',
        VIDEO_INVITE_ACCEPT: 'Accept',
        VIDEO_INVITE_NOTIFICATION_TITLE: 'Video invite',
        VIDEO_INVITE_REJECT: 'Reject',
        VIDEO_INVITE_TEXT: 'is inviting you to a video chat session',
        VIEW_MODE: 'View mode',
        VISUALIZE_ASSEMBLY: 'Visualize assembly',
        VISUALIZE_PRODUCT: 'Visualize product',
        WARNINGS: 'Warnings:',
        WAITING_REMOTE_VIDEO: 'Waiting for remote video.',
        WAITING_USER_MEDIA: 'Waiting user media ... Please accept the prompt from your browser.',
        USED_BY: 'Used by',
        WITHDRAW_INVITATION: 'Withdraw invitation',
        WITH_LINKS: 'With links',
        WITHOUT_LINKS: 'Without links',
        WORKFLOW_HISTORY: 'History',
        WORKFLOW_LEGEND_COMPLETE: 'Complete',
        WORKFLOW_LEGEND_INCOMPLETE: 'Incomplete',
        WORKFLOW_LEGEND_INPROGRESS: 'In progress',
        WORKFLOW_LEGEND_REJECTED: 'Rejected',
        WORKFLOW_NAME_PLACEHOLDER: 'Workflow name',
        WORKFLOW: 'Workflow',
        WORKFLOW_COPY: 'Workflow copy',
        WORKFLOWS: 'Workflows',
        WORKSPACES_ADMINISTRATION: 'Workspaces administration',
        WORKSPACE_MANAGEMENT: 'Workspace administration',
        WORKSPACES: 'Workspaces',
        WORKSPACE: 'Workspace',
        YOU_CANNOT_CREATE_LINK_WITHOUT_TYPE: 'You cannot create a link without a type',
        YOU_HAVE_BEEN_KICKED: 'You have been kicked from the collaborative room',
        LANGUAGES: {
            fr: 'French',
            en: 'English',
            ru: 'Russian'
        }
    }
});
