/*global define*/
define({
    root: {
        ABOUT_DOCDOKUPLM: 'Информация о DocDokuPLM',
        ABSOLUTE: 'Абсолютно',
        ACCEPT_VIDEO_INVITE: 'Принять',
        ACCESS_RIGHTS: 'Приянть правила',
        ACL: 'ACL',
        ACTIVITY_STATE_PLACEHOLDER: 'Новое состояние',
        ADD_ACTIVITY: 'Добавить действие',
        ADD: 'Добваить',
        ADD_CALCULATION: 'Добавить вычисление',
        ADD_COMMENT: 'Добавить комментарий',
        ADD_DOCUMENT: 'Добавить документ',
        ADD_DOCUMENTS_TO_BASELINE: 'Добавить документ в постоянную коллекцию',
        ADD_ISSUE: 'Добавить проблему',
        ADD_NEW_TAG: 'Добавить новый тэг',
        ADD_NOTIFICATION: 'Добавить уведомление',
        ADD_PART: 'Добавить деталь',
        ADD_REQUEST: 'Добавить запрос',
        ADD_REVISION_NOTE: 'Добавить примечание',
        ADD_TASK: 'Добавить задачу',
        ADD_TEMPLATE_ATTRIBUTES: 'Добавить атрибут поставки',
        ADMINISTRATED: 'Администрировать',
        ADVANCED: 'Дополнительно',
        ADVANCED_SEARCH: 'Расширенный поиск',
        AFFECTED_ELEMENT: 'Затрагиваемый элемент',
        ALERT_ROLE_IN_USE: 'Эта роль не может быть удалена, потому что используется в каком-то потоке работ',
        ALL: 'Все',
        ALL_PRODUCTS: 'Все изделия',
        ALL_TASKS: 'Все задачи',
        AMOUNT: 'Количество',
        APPEND: 'Добавить',
        APPEND_LAYER: 'Создать новый слой',
        APPROVE_TASK: 'Пометить задачу как выполненная',
        ASSIGNED_ROLE_PRE_FILL: 'Назначение по умолчанию',
        ASSIGNED_ROLE_REQUIRED: 'Вы должны назначить хотя бы одного пользователя или группу',
        ASSIGNED_USERS: 'Назначенные пользователи',
        ASSIGNED_USERS_PRE_FILL: 'Предварительное заполнение пользователей по умолчанию',
        ASSIGNED_USERGROUPS: 'Назначенные группы',
        ASSIGNED_USERGROUPS_PRE_FILL: 'Предворительное заполнение групп по умолчанию',
        ASSIGNMENTS: 'Назначения',
        ATTACHED_FILES: 'Прикрепленные файлы',
        ATTRIBUTES: 'Атрибуты',
        AUTHOR: 'Автор',
        AUTHOR_LOGIN: 'Логин автора',
        AUTHOR_NAME: 'Имя автора',
        AUTHOR_DOCUMENT_HELP: 'Автор документа или пользователь работавший над этим документом',
        AUTHOR_PART_HELP: 'Автор детали или пользователь работавший над этим деталью',
        AUTO_CHECKIN: 'Автоматически регистрировать детали которые были разрегистрированы во время импорта',
        AUTO_CHECKOUT: 'Автоматически разрегистрировать если необходимо',
        AVG: 'Среднее',
        BACK: 'Назад',
        BASED_ON: 'Основывается на',
        BASELINE: 'Базовая линия',
        BASELINE_DELETION_ERROR: 'Нельзя удалить базовую линию : ',
        BASELINE_OF: 'Базовая линия',
        BASELINES: 'Базовые линии',
        BEST_FIT_VIEW: 'Наилучший вид',
        BLOCKER_TEXT: '(Z, Q, S, D = Перемещение, SPACE = Вверх, CTRL = Вниз, MOUSE = Повернуть вокруг, ESC = Выйти)',
        BLOCKER_TITLE: 'Нажмите чтобы запустить сцену',
        BOM_VIEW: 'Спецификация',
        BOOLEAN: 'Логический',
        BY: 'by',
        CAD_FILE: 'CAD файл',
        CAD_FILES: 'CAD файлы',
        CALCULATIONS: 'Расчеты',
        CALL_TO_TITLE: 'Обратиться к',
        CANCEL: 'Отмена',
        CANCEL_CHECKOUT: 'Отменить разрегистрацию',
        CANCEL_PART_CREATION: 'Отметить создание детали',
        CANNOT_CREATE_PC: 'Невозможно создать объект RTCPeerConnection, WebRTC не поддерживается этим браузером.',
        CANNOT_DELETE_FILE: 'Невозможно удалить файл : ',
        CHANGE_ITEM_ASSIGNEE: 'Назначение',
        CHANGE_ITEM_CATEGORY: 'Категория',
        CHANGE_ITEM_PRIORITY: 'Приоритет',
        CHANGES: 'Редактировать управление',
        CHANGE_MANAGEMENT: 'Редактировать управление',
        CHANNEL_NOT_READY_ERROR: 'Не удается установить связь с сервером вызовов. Пожалуйста, убедитесь, что ваш браузер поддерживает websocket, или ваш интернет-провайдер не блокирует их.',
        CHECK_ALL: 'Проверить все',
        CHECKED_IN: 'Загеристрировано',
        CHECKIN: 'Зарегистрировать',
        CHECKIN_DATE: 'Дата регистрации',
        CHECKOUT_BY: 'Разрегистрировал',
        CHECKOUT: 'Разрегистрировано',
        CHECKOUT_DATE: 'Дата разрегистрации',
        CHECKOUTS: 'Разрегистрировано',
        CHOICES: 'Выбор',
        CHOOSE_A_PRODUCT: 'Выбранный продук',
        CHOSEN_OPTIONALS: 'Исключенный опции',
        CHOSEN_SUBSTITUTES: 'Выбранные заменители',
        CLEAR: 'Очистить',
        CLIPPING: 'Обрезка',
        CLOSE: 'Закрыть',
        CLOSING_PEER_CON: 'Закрытие подключение ...',
        CLOSURE_COMMENT: 'Закрыть комментарий',
        COLLABORATIVE: 'Общий доступ',
        COLLABORATIVE_INVITE: 'Вас приглашают присоединиться к комнате',
        COLLABORATIVE_KICKED: 'Вы были выкинуты из комнаты',
        COLLABORATIVE_LEAD: 'Ведущий',
        COLLABORATIVE_NO_MASTER: 'Отсутствует',
        COLLABORATIVE_NOT_INVITED: 'Вы не приглашены в эту комнату',
        COLLABORATIVE_WITHDRAW_INVITATION: 'Приглашение отменено',
        COMMENT: 'Комментарий',
        COMPONENT_SELECTED: 'Выделенная деталь',
        CONFIG_SPEC: 'Конфигурировать спецификацию',
        CONFIGURATION: 'Конфигурация',
        CONFIGURATIONS: 'Конфигурации',
        CONFIRM: 'Подтвердить',
        CONFIRM_IMPORT: 'Подтвердить импорт?',
        CONFIRM_IMPORT_WITH_OPTION: 'Подтвердить импорт с опциями:',
        CONFIRM_PASSWORD: 'Подтвердить пароль',
        CONNECTED: 'Подключено',
        CONNECTING: 'Подключение...',
        CONTAINS_OBSOLETE_PARTS: 'Содержит устаревшие детали',
        CONTENT: 'Содержание',
        CONTENT_HELP: 'Содержание файла(ов)',
        CONTROLS_SHORTCUTS: 'Горяие клавишы мыши/клавиатуры',
        CONVERSION: 'Преобразование',
        CONVERSION_STATUS: 'Изменение статуса',
        CONVERSION_PENDING: 'Ожидание перехода',
        CONVERSION_SUCCEED: 'Переход успешный',
        CONVERSION_FAILED: 'Переход не удался',
        COPY: 'Копировать',
        COWORKERS: 'Сотрудники',
        CREATE: 'Создать',
        CREATE_BASELINE: 'Создать базовую линию',
        CREATE_DOCUMENT_COLLECTION: 'Создание коллекции документов',
        CREATE_NEW_EFFECTIVITY: 'Создать новую применяемость',
        CREATE_NEW_EFFECTIVITY_ERROR: 'Применяемость не создана',
        CREATE_NEW_EFFECTIVITY_SUCCESS: 'Применяемость создана',
        CREATE_NEW_PART: 'Создать новую деталь',
        CREATE_NEW_PART_AS_SUBSTITUTE: 'Создать новую деталь как замену',
        CREATE_NEW_VERSION: 'Создать новую версию',
        CREATE_PART: 'Создать деталь',
        CREATE_PART_SUBSTITUTE_TOOLTIP: 'Чтобы создать заменяющую ссылку, сначала необходимо выбрать для чего создается ссылка',
        CREATE_PART_TOOLTIP: 'Чтобы создать новую ссылку использования, не один из элементов не должен быть выбран',
        CREATE_PRODUCT: 'Создать изделие',
        CREATE_ROOM: 'Начать обзор цифрового макета',
        CREATION_DATE: 'Дата создания',
        CREATION_ERROR: 'Произошла ошибка во время создания',
        CURRENT_TAGS: 'Теги связанные с',
        CURRENT_WORKFLOW: 'Текущий поток работ',
        CUTPLAN: 'План разреза',
        DATE: 'Дата',
        _DATE_FORMAT: 'MM-DD-YYYY HH:mm:ss',
        _DATE_PICKER_DATE_FORMAT: 'YYYY-MM-DD',
        _DATE_SHORT_FORMAT: 'MM-DD-YYYY',
        DATE_SORT: 'date_sort',
        DBL_CLICK: 'Двойной клик',
        DELETE_ACTIVITY: 'Удалить действие',
        DELETE: 'Удалить',
        DELETE_FOLDER_QUESTION: 'Удалить папку?',
        DELETE_LINKED_ITEM: 'Удалить ссылку',
        DELETE_MARKER: 'Удалить маркер',
        DELETE_PRODUCT_CONFIRM: 'Вы действительно хотите удалить это изделие?',
        DELETE_PRODUCT: 'Удалить изелие',
        DELETE_PRODUCT_ERROR: 'Ошибка при удаление изделия',
        DELETE_SELECTION: 'Удалить выбранное',
        DELETE_SELECTION_QUESTION: 'Удалить выбранное',
        DELETE_TAG_QUESTION: 'Удалить выбранный тег?',
        DELETE_QUERY_QUESTION: 'Удалить выбранный запрос?',
        DELETE_TASK: 'Удалить задачу',
        DESCRIPTION: 'Описание',
        DEVICE_ERROR: 'Невозможно получить доступ к вашему аудио/видео устройству, пожалуйста, выберите браузер поддерживащий WebRTC, и если на этом веб-сайте нет исключения.',
        DISPLAY_COMMENTS: 'Скрыть/показать определение',
        DOCUMENT: 'Документ',
        DOCUMENT_REVISION_NOTE_PROMPT_LABEL: 'Вы хотите добавить примечание к документу без него?',
        DOCUMENT_S_DESCRIPTION: 'Описание документа',
        DOCUMENT_S_REFERENCE: 'ID документа',
        DOCUMENT_S_TITLE: 'Заголовок документа',
        DOCUMENT_TEMPLATES: 'Шаблон документа',
        DOCUMENT_TYPE_HELP: 'Тип документа',
        DOCUMENT_VERSION_HELP: 'Версия документа',
        DOCUMENTS: 'Документы',
        DOCUMENTS_CHOICE: 'Выбранные документы',
        DOCUMENTS_CHOICE_EXPLANATION: 'Выберите несколько документы из папки',
        DOCUMENT_COLLECTION: 'Колекция документов',
        DOCUMENT_COLLECTION_IN_PROGRESS: 'Колекция документов в процессе',
        DOCUMENT_COLLECTIONS: 'Колекции документов',
        DOCUMENT_MANAGEMENT: 'Управление документами',
        DOWNLOAD_DPLM_CLIENT: 'Скачать DPLM клиент',
        DOWNLOAD_ZIP: 'Скачать все файлы в ZIP',
        DROP_FILE_HERE: 'или удалить его здесь',
        DROP_FILES_HERE: 'или удалить их здесь',
        DUE_DATE: 'срок',
        DUPLICATE: 'Дубликат',
        DUPLICATE_WORKFLOW: 'Дублировать поток работ',
        EDIT_BASELINE: 'Редактировать базовую линию',
        EDIT: 'Редактировать',
        EDIT_ISSUE: 'Редактировать ошибку',
        EDIT_LINKED_DOCUMENTS: 'Редактировать ссылку',
        EDIT_MILESTONE: 'Редактировать веху',
        EDIT_ORDER: 'Редактировать заказ',
        EDIT_PRODUCT: 'Редактировать изделие',
        EDIT_PRODUCT_INSTANCE: 'Редактировать доставку',
        EDIT_REQUEST: 'Редактировать запрос',
        EDITION_ERROR: 'Произошла ошибка во время редактирования',
        EFFECTIVITY: 'Применяемость',
        EFFECTIVITY_DATE: 'Дата',
        EFFECTIVITY_DESCRIPTION: 'Описание',
        EFFECTIVITY_END_DATE: 'Дата окончания',
        EFFECTIVITY_END_LOT_ID: 'Конечная партия',
        EFFECTIVITY_END_NUMBER: 'Конец серийного номера',
        EFFECTIVITY_LOT: 'Базовая партия',
        EFFECTIVITY_NAME: 'Название',
        EFFECTIVITY_SERIAL_NUMBER: 'Базовый серийный номер',
        EFFECTIVITY_START_DATE: 'Дата начала',
        EFFECTIVITY_START_LOT_ID: 'Начальная партия',
        EFFECTIVITY_START_NUMBER: 'Начало серийного номера',
        EFFECTIVITY_TYPE: 'Тип применяемости',
        EMBED_SCENE: 'Вставить сцены',
        EMAIL: 'Email',
        EMPTY_CHOICES: 'Нельзя создать конфигурацию без выбранной детали',
        // EMPTY_REVISION_NOTE: 'Empty revision note.Please uncheck option or write note',
        EMPTY_REVISION_NOTE: 'Пустое примечание. Пожалуйста, отключите опцию или напишите примечание',
        END: 'Конец',
        ENTER_NAV: 'Начать навигацию',
        ERROR: 'Ошибка',
        ERRORS: 'Ошибки:',
        ERROR_404: 'ERROR 404. Мы не смогли найти то, что вы ищете...',
        ERROR_404_SORRY: 'Извините !',
        EXISTING_TAGS: 'Доступные теги',
        EXIT: 'Закончить обзор цифрового макет',
        EXPIRE_DATE: 'Срок годности',
        EXPLODE: 'Развернуть',
        EXPORT: 'Экспорт',
        EVERYTHING: 'Все',
        FALSE: 'False',
        FILE: 'File',
        FILE_DELETION_ERROR: 'The file %{id} could not be deleted',
        FILE_UPLOADED: 'The file has been uploaded',
        FILES_UPLOADED: 'The files have been uploaded',
        FILES: 'Files',
        FILL: 'Fill',
        FILTER: 'Filter',
        FINAL_STATE_PLACEHOLDER: 'Final state',
        FIRST_PAGE: 'First page',
        FIT_VIEW: 'Fit view',
        FLYING_MODE: 'Fly mode',
        FLY_TO: 'Fly to',
        FOLDER: 'Folder',
        FOLDERS: 'Folders',
        FOLDER_S_NAME: 'Folder name',
        FOLD_TASK: 'Minimize task',
        FORBIDDEN: 'Forbidden',
        FORBIDDEN_MESSAGE: 'You cannot access to this resource, you need to log in before continue',
        FORM_HELPER: 'Leave these inputs empty if you don\'t want to specify a password or an expiration date',
        FREEZE_CURRENT_ITERATION: 'Freeze current iteration',
        FREEZE_AFTER_MODIFICATION: 'Freeze iterations after modification',
        FROM: 'From',
        FULL_ACCESS: 'Full access',
        FULL_SCREEN: 'Full screen',
        GENERAL: 'General',
        GENERATED_URL: 'Generated url',
        GIVE_HAND: 'Give the hand',
        GO_TO_PAGE: 'Go to page ...',
        GOTO_PARALLEL_MODE: 'Switch activity to parallel',
        GOTO_SEQUENTIAL_MODE: 'Switch activity to sequential',
        GRID_SWITCH: 'Show/Hide the grid',
        GROUPS: 'Groups',
        HAS_SUBSTITUTES: 'Has substitutes',
        HEAD_CHECKIN: 'Latest checked in',
        HEAD_RELEASED: 'Latest released',
        HEAD_WIP: 'Work in progress',
        HIDE_SUBSTITUTES: 'Hide substitutes',
        HOME_PAGE: 'Home',
        HOURS: 'h',
        HISTORY: 'History',
        ID_GENERATION: 'Id generation',
        IGNORE: 'Ignore',
        IMPORT_ATTRIBUTE_FILE: 'Import attribute\'s file',
        IMPORT_DELIVERABLE_DATA: 'Import deliverable data',
        IMPORT_PART_DATA: 'Import part data',
        IMPORTER: 'Import',
        IMPORT_PENDING: 'Import pending',
        IMPORT_SUCCEED: 'Import succeed',
        IMPORT_FAILED: 'Import failed',
        INIT_VALUE: 'Init value',
        IN_PROGRESS: 'Work in progress',
        INITIATOR: 'Initiator',
        INSTANCE_SELECTED: 'Selected instance',
        INSTRUCTIONS: 'Instructions',
        INVERT_SOURCE_DESTINATION: 'Invert source and destination',
        INVITE: 'Invite coworkers',
        ISSUES: 'Issues',
        IS_COMPONENT_OF: 'Is component of :',
        IS_SUBSTITUTE_IN: 'Is substitute in :',
        IS_SUBSTITUTE: 'Is substitute',
        ITERATION_CHANGE: 'Iteration change',
        ITERATION: 'Iteration',
        KEYBOARD_SHORTCUTS: 'Keyboard shortcuts',
        KG: 'kg',
        LAST_ITERATION: 'Current iteration',
        LAST_PAGE: 'Last page',
        LATEST: 'Latest',
        LATEST_SHORT: 'Latest versions',
        LAYERS: 'Layers',
        LEAVE_NAV: 'Stop the navigation',
        LEFT_CLICK: 'left click',
        LIFECYCLE_STATE: 'Life cycle state',
        LINK_DESCRIPTION: 'Link description',
        LINKED_DOCUMENTS: 'Linked documents',
        LINKS: 'Links',
        LOADING: 'Loading',
        LOCK_ATTRIBUTES: 'Freeze attributes structure',
        LOCKED: 'Locked',
        LOGIN: 'Login',
        LOGOUT: 'Logout',
        LOOK_AT: 'Look at',
        MANAGE_PRODUCT: 'Products management',
        MANAGE_ROLES: 'Manage roles',
        MANDATORY: 'Mandatory',
        MARK_ALL_AS_VERIFIED: 'Mark all as verified',
        MARK_AS_VERIFIED: 'Mark as verified',
        MARK_AS_OBSOLETE: 'Mark as obsolete',
        MARK_DOCUMENT_AS_OBSOLETE_QUESTION: 'Mark as obsolete the selected document?',
        MARK_PART_AS_OBSOLETE_QUESTION: 'Mark as obsolete the selected part?',
        MARKER_INFO: 'Get marker informations',
        MARKERS: 'Markers',
        MARKERS_OPACITY: 'Change markers opacity',
        MARKERS_SIZE_MAX: 'Increase markers size',
        MARKERS_SIZE_MIN: 'Reduce markers size',
        MASK_HELP: 'Define the mask format for the IDs of documents/parts that will instanciate this template.\n\nAdditionally to any regular characters, you can use \'#\' symbol for any valid number and \'*\' for any character.\n\nFor instance \'FAX-***-##\' will accept \'FAX-AZE-12\' as a valid ID.\n\nA mask wihtout any wildcards character won\'t be usable more than once.',
        MASK: 'Mask',
        MEASURE: 'Measure',
        METER: 'm',
        MILESTONE: 'Milestone',
        MILESTONES: 'Milestones',
        MODIFICATION_DATE: 'Modification date',
        MODIFICATION_NOTIFICATION_LIST_DESCRIPTION: 'Subcomponents changelog',
        MOUSE_CONTROLS: 'Mouse controls',
        MOVE: 'move',
        MOVE_BACKWARD: 'Move backward',
        MOVE_DOWN: 'Move down',
        MOVE_FORWARD: 'Move forward',
        MOVE_LEFT: 'Move left',
        MOVE_RIGHT: 'Move right',
        MOVE_SCENE: 'Move into the scene',
        MOVE_UP: 'Move up',
        MULTIPLE_VERSIONS_FOR_DOCUMENT: 'This document has already been added with a different version',
        MY_ACCOUNT: 'My account',
        MY_ORGANIZATION: 'My organization',
        MY_WORKSPACES: 'My workspaces',
        NAME: 'Name',
        NAVIGATION: 'Navigation',
        NB_TASKS_TO_COMPLETE: 'Tasks to complete',
        NEW_BASELINE: 'New baseline',
        NEW_CONFIGURATION: 'New configuration',
        NEW_DOCUMENT: 'New document',
        NEW_DOCUMENT_COLLECTION: 'New document collection',
        NEW_EFFECTIVITY: 'New effectivity',
        NEW_FOLDER: 'New folder',
        NEW_ISSUE: 'New change issue',
        NEW_LAYER: 'New layer',
        NEW_LINK_TYPE: 'Create new type',
        NEW_MARKER: 'New marker',
        NEW_MILESTONE: 'New milestone',
        NEW_ORDER: 'New change order',
        NEW_PART: 'New part',
        NEW_PART_TEMPLATE: 'New part template',
        NEW_PRODUCT_INSTANCE: 'New deliverable',
        NEW_PRODUCT: 'New product',
        NEW_REQUEST: 'New change request',
        NEW_ROLE: 'New role',
        NEW_TAG: 'New tag',
        NEW_TEMPLATE: 'New document template',
        NEW_UNIT: 'Unit',
        NEW_VERSION: 'New version',
        NEW_VERSION_OF: 'New version of',
        NEW_WORKFLOW: 'New workflow',
        NEXT_PAGE: 'Next page',
        NO_CONVERSION: 'No conversion',
        NO_COWORKER: 'No coworker',
        NO_DATA: 'No data available in table',
        NO_FILE_TO_IMPORT: 'No file to import',
        NO_FILTERED_DATA: 'No matching records found',
        NO_LAYERS: 'No layers',
        NO_PARTICIPANT: 'No participant. Invite users from Coworkers menu.',
        NOTIFICATIONS: 'Notifications',
        NOTHING_HERE: 'There\'s nothing here, the url link is incorrect',
        NOT_INVITED_COLLABORATIVE_ROOM: 'You are not invited to join this room.',
        NOT_VERIFIED: 'Not verified',
        NO_WEBGL: 'No WebGL available or activated',
        NOT_YET_REGISTERED_QUESTION: 'Not a registered user?',
        NOT_YET_REGISTERED_REGISTER: 'sign up!',
        NODE_ASSEMBLIES_VISITED: 'Visited assemblies',
        NODE_INSTANCES_VISITED: 'Visited instances',
        NONE: 'None',
        NOTIFY_BY_TAG: 'Notify user(s) about changes on items tagged with...',
        NUMBER: 'Number',
        LITER: 'l',
        LIST_LOV: 'Edit lists of values',
        LOCK: 'Lock',
        LOV: 'List of values',
        OBSOLETE: 'Obsolete',
        OBSOLETE_AUTHOR: 'Obsolete status author',
        OBSOLETE_DATE: 'Obsolete status date',
        OFFICIAL_SITE: 'PLM community',
        OFFLINE: 'Offline',
        OK: 'OK',
        ON: 'on',
        OR: 'or',
        ONLINE: 'Online',
        OPEN_NEW_WINDOW: 'Open in a new window',
        OPTIONAL: 'Optional',
        OPTIONAL_REMOVE: 'None',
        OPTIONS: 'Options',
        OR_ADD_PART: 'Or add an existing part',
        ORBIT_MODE: 'Orbit mode',
        ORDERS_NUMBER: 'Number of orders',
        ORDERS: 'Orders',
        OTHERS: 'Others',
        PATH_TO_PATH_LINKS: 'Typed links',
        PARALLEL_ACTIVITY: 'In parallel, requires ',
        PART_ATTRIBUTES: 'Part attributes',
        PART_ATTRIBUTES_TEMPLATES: 'Templates of part attributes',
        PARTICIPANT: 'Participant',
        PART_DESCRIPTION: 'Description',
        PART_NAME: 'Part name',
        PART_NOT_FOUND: 'The root part has not been found',
        PART_NUMBER_HELP: 'Number of the part',
        PART_NUMBER: 'Part number',
        PARTS: 'Parts',
        PART_REVISION_NOTE_PROMPT_LABEL: 'Do you want to add a revision note to parts without one?',
        PART_SEARCH_HELP: 'text',
        PART_SUBSTITUTE: 'substitute part',
        PARTS_SUBSTITUTES: 'substitute parts',
        PART_TEMPLATE: 'Part template',
        PART_TEMPLATES: 'Templates',
        PART_TYPE_HELP: 'Type of the part',
        PART_VERSION_HELP: 'Version of the part',
        PASSWORD_NOT_CONFIRMED: 'Password and Confirm password must match',
        PASSWORD: 'Password',
        PATH: 'Folder',
        PATH_TO_PATH_SOURCE: 'Source',
        PATH_TO_PATH_TARGET: 'Target',
        PATH_TO_PATH_SOURCE_LINK: 'Source links',
        PATH_TO_PATH_TARGET_LINK: 'Target links',
        PENDING: 'Absent participant',
        PERMALINK: 'Permalink',
        PERMISSIVE_UPDATE_PART: 'Permissive update (only modifiable parts will be considered)',
        PERMISSIVE_UPDATE_PATH_DATA: 'Permissive update (only modifiable deliverable data will be considered)',
        POSSIBLE_VALUE: 'possible values',
        PREVIOUS_PAGE: 'Previous page',
        PRIVATE_SHARE_TITLE: 'Private share',
        PRODUCT: 'Product',
        PRODUCT_ID: 'Product Id',
        PRODUCT_INSTANCE: 'Deliverable',
        PRODUCT_INSTANCES: 'Deliverables',
        PRODUCT_INSTANCE_DATA: 'Deliverable data',
        PRODUCT_INSTANCE_DATA_ATTRIBUTES: 'Deliverable data attributes',
        PRODUCT_INSTANCE_DATA_ATTRIBUTES_TEMPLATES: 'Templates of deliverable data attributes',
        PRODUCT_NAME: 'Product name',
        PRODUCT_MANAGEMENT: 'Product management',
        PRODUCTS: 'Products',
        PRODUCT_STRUCTURE: 'Product structure',
        PROTECTED_RESOURCE: 'This resource is password protected',
        PUBLIC_ACCESS_TITLE: 'Public access to permalink',
        PUBLIC_SHARE: 'Public share',
        PUBLISH: 'Publish',
        QUERY_EXPORT_EXCEL_LOADING: 'Export...',
        QUERY_EXPORT_EXCEL: 'Export Excel',
        QUICK_SEARCH: 'Quick search',
        QUERY_STANDARD: 'Standard',
        QUERY_BUILDER_CONDITION_AND: 'AND',
        QUERY_BUILDER_CONDITION_OR: 'OR',
        QUERY_BUILDER_OPERATORS_EQUALS: 'equal',
        QUERY_BUILDER_OPERATORS_NOT_EQUALS: 'not equal',
        QUERY_BUILDER_OPERATORS_IN: 'in',
        QUERY_BUILDER_OPERATORS_NOT_IN: 'not in',
        QUERY_BUILDER_OPERATORS_LESS: 'less',
        QUERY_BUILDER_OPERATORS_LESS_OR_EQUAL: 'less or equal',
        QUERY_BUILDER_OPERATORS_GREATER: 'greater',
        QUERY_BUILDER_OPERATORS_GREATER_OR_EQUAL: 'greater or equal',
        QUERY_BUILDER_OPERATORS_BETWEEN: 'between',
        QUERY_BUILDER_OPERATORS_BEGIN_WITH: 'begins with',
        QUERY_BUILDER_OPERATORS_NOT_BEGIN_WITH: 'doesn\'t begin with',
        QUERY_BUILDER_OPERATORS_CONTAINS: 'contains',
        QUERY_BUILDER_OPERATORS_NOT_CONTAINS: 'doesn\'t contain',
        QUERY_BUILDER_OPERATORS_ENDS_WITH: 'ends with',
        QUERY_BUILDER_OPERATORS_NOT_ENDS_WITH: 'doesn\'t end with',
        QUERY_BUILDER_OPERATORS_IS_EMPTY: 'is empty',
        QUERY_BUILDER_OPERATORS_IS_NOT_EMPTY: 'is not empty',
        QUERY_BUILDER_OPERATORS_IS_NULL: 'is null',
        QUERY_BUILDER_OPERATORS_IS_NOT_NULL: 'is not null',
        QUERY_BUILDER_ERRORS_NO_FILTER: 'No filter selected',
        QUERY_BUILDER_ERRORS_EMPTY_GROUP: 'The group is empty',
        QUERY_BUILDER_ERRORS_RADIO_EMPTY: 'No value selected',
        QUERY_BUILDER_ERRORS_CHECKBOX_EMPTY: 'No value selected',
        QUERY_BUILDER_ERRORS_SELECT_EMPTY: 'No value selected',
        QUERY_BUILDER_ERRORS_STRING_EMPTY: 'Empty value',
        QUERY_BUILDER_ERRORS_STRING_EXCEED_MIN_LENGTH: 'Must contain at least {0} characters',
        QUERY_BUILDER_ERRORS_STRING_EXCEED_MAX_LENGTH: 'Must not contain more than {0} characters',
        QUERY_BUILDER_ERRORS_STRING_INVALID_FORMAT: 'Invalid format ({0})',
        QUERY_BUILDER_ERRORS_NUMBER_NAN: 'Not a number',
        QUERY_BUILDER_ERRORS_NUMBER_NOT_INTEGER: 'Not an integer',
        QUERY_BUILDER_ERRORS_NUMBER_NOT_DOUBLE: 'Not a real number',
        QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MIN: 'Must be greater than {0}',
        QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MAX: 'Must be lower than {0}',
        QUERY_BUILDER_ERRORS_NUMBER_WRONG_STEP: 'Must be a multiple of {0}',
        QUERY_BUILDER_ERRORS_DATETIME_EMPTY: 'Empty value',
        QUERY_BUILDER_ERRORS_DATETIME_INVALID: 'Invalid date format ({0})',
        QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MIN: 'Must be after {0}',
        QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MAX: 'Must be before {0}',
        QUERY_BUILDER_ERRORS_BOOLEAN_NOT_VALID: 'Not a boolean',
        QUERY_BUILDER_ERRORS_OPERATOR_NOT_MULTIPLE: 'Operator {0} cannot accept multiple values',
        QUERY_GROUP_AUTHOR: 'Author',
        QUERY_GROUP_PART_MASTER: 'Part Master',
        QUERY_GROUP_PART_REVISION: 'Part Revision',
        QUERY_GROUP_PRODUCT: 'Product',
        QUERY_GROUP_ATTRIBUTE_STRING: 'String attribute',
        QUERY_GROUP_ATTRIBUTE_LONG_STRING: 'Long string attribute',
        QUERY_GROUP_ATTRIBUTE_PART_NUMBER: 'Part number attribute',
        QUERY_GROUP_ATTRIBUTE_LOV: 'List of values attribute',
        QUERY_GROUP_ATTRIBUTE_URL: 'URL attribute',
        QUERY_GROUP_ATTRIBUTE_NUMBER: 'Number attribute',
        QUERY_GROUP_ATTRIBUTE_DATE: 'Date attribute',
        QUERY_GROUP_ATTRIBUTE_BOOLEAN: 'Boolean attribute',
        QUERY_GROUP_CONTEXT: 'Context',
        QUERY_GROUP_PATH_DATA_ATTRIBUTE: 'Deliverable attribute',
        QUERY_NAME: 'Query name',
        QUERY_SEARCH: 'Build a query',
        QUERY_SELECT: 'Select',
        QUERY_CONTEXT: 'Context',
        QUERY_WHERE: 'Where',
        QUERY_WHERE_CONTEXT: 'Deliverable data filters',
        QUERY_ORDER_BY: 'Order by',
        QUERY_GROUP_BY: 'Group by',
        QUERY_CLEAR: 'clear',
        QUERY_REMOVE_SAVED_QUERY: 'Delete from queries list',
        QUERY_CHOOSE_EXISTING_REQUEST: 'Or use an existing one...',
        QUERY_CONTEXT_ERROR: 'Can\'t retrieve products',
        QUERY_ATTRIBUTES_ERROR: 'Can\'t retrieve attribute list',
        QUERY_FILTER_STATUS_WIP: 'Work in progress',
        QUERY_FILTER_STATUS_RELEASED: 'Released',
        QUERY_FILTER_STATUS_OBSOLETE: 'Obsolete',
        QUERY_DEPTH: 'Depth',
        READ_ONLY: 'Read only',
        REBASE: 'Rebase',
        REBASE_AUTHOR: 'Rebase author',
        REBASE_SUCCESS: 'The deliverable has been rebased',
        REFERENCE_HELP: 'Document ID',
        REFERENCE: 'ID',
        REFRESH_TREE: 'Refresh tree',
        REJECT_TASK: 'Reject task',
        REJECT_VIDEO_INVITE: 'Reject',
        RELATIVE: 'Relative',
        RELAUCNH_ACTIVITY_SELECTOR: 'Relaunch activity if rejected',
        RELEASE_DATE: 'Release date',
        RELEASED_BY: 'Released by',
        RELEASED: 'Released',
        RELEASED_SHORT: 'Latest released versions',
        RELEASE: 'Release',
        RELEASE_NOW: 'Release now',
        RELEASE_SELECTION_QUESTION: 'Release selection?',
        RELOAD: 'Reload',
        REMOTE_ACCEPT: 'Remote user has accepted the call. Waiting for connection ...',
        REMOTE_BUSY: 'Remote user is busy. Call aborted ...',
        REMOTE_HANGUP: 'Remote user hang up',
        REMOTE_OFFLINE: 'Remote user is offline. Call ended ...',
        REMOTE_REJECT: 'Remote user has rejected the call. Call ended ...',
        REMOTE_STEAM_ADDED: 'Remote stream added',
        REMOTE_STEAM_REMOVED: 'Remote stream removed',
        REMOTE_TIMEOUT: 'Remote user didn\'t answer in time. Call aborted ...',
        REMOVE_DOCUMENT_FROM_COLLECTION: 'Remove document from collection',
        RENAME: 'Rename',
        RENAME_WORKFLOW_COPY: 'Name of the copy',
        REPLACE: 'Reset',
        REQUESTS_NUMBER: 'Number of request',
        REQUESTS: 'Requests',
        REQUIRED_FIELD: 'Please fill out this field',
        RESET: 'Reset',
        RESET_CAMERA: 'Reset camera',
        RESULT: 'Result',
        RETAIN: 'Retain',
        RETRY: 'Retry',
        REVISION_DATE: 'Revision date',
        REVISION_NOTE: 'Revision note',
        REVISION_NOTE_PROMPT_CANCEL: 'Ignore',
        REVISION_NOTE_PROMPT_LABEL: 'Do you want to add a revision note?',
        REVISION_NOTE_PROMPT_OK: 'Add revision note',
        RIGHT_CLICK: 'right click',
        ROLE_NAME: 'Role name',
        ROLE: 'Role',
        ROLES: 'Roles',
        ROOT_PART: 'Root part',
        ROTATE: 'Rotate',
        ROTATE_SCENE: 'Rotate the scene',
        RUN: 'Run',
        SAVED: 'Saved',
        SAVE: 'Save',
        SCALE: 'Scale',
        SCENE_VIEW: 'Scene view',
        SCROLL_DOWN: 'scroll down',
        SCROLL_UP: 'scroll up',
        SEARCH_OPTIONS: 'Search options by number or name',
        SEARCH_PART_BEGINNING: 'Search part beginning by',
        SEARCH_PART_CALLED: 'Search part called',
        SEARCH_PART_ENDING: 'Search part ending by ',
        SEARCH_PARTS: 'Search parts',
        SEARCH: 'Search',
        SEARCHING: 'Searching...',
        SEARCHING_FOR_PARTS: 'Searching for parts, please do not close the window...',
        SECONDS: 's',
        SEE_IN_DOCUMENT_MANAGEMENT: 'See the document in the document management module',
        SEE_IN_PRODUCT_MANAGEMENT: 'See the part in the product management module',
        SELECT_FILE: 'Choose a file',
        SELECT_FILES: 'Choose one or more file(s)',
        SEND: 'Send',
        SEQUENTIAL_ACTIVITY: 'In sequential',
        SERIAL_NUMBER: 'Serial number',
        SESSION_CONNECTING: 'Session connecting',
        SESSION_OPENED: 'Session opened',
        SERVER_NOT_AVAILABLE: 'Server isn\'t available, please try again',
        SHARED_DOCUMENTS_TITLE: 'Share document',
        SHARED_PARTS_TITLE: 'Share part',
        SHARE: 'Share',
        SHORTCUTS_TITLE: 'Keyboard / mouse shortcuts',
        SHOW_ALL: 'Show all',
        SHOW_BY_PAGE: 'Show by page',
        SHOW_EDITED_MESHES: 'Highlight edited meshes',
        SHOW_SUBSTITUTES: 'Show substitutes',
        SIGN_TASK: 'Signing up',
        SINGLE_FILE_RESTRICTION: 'Only one file is allowed',
        SORRY: 'Sorry',
        SPACE: 'space',
        SQUARE_METER: 'm²',
        STANDARD_PART_ALL: 'All',
        STANDARD_PART_FALSE: 'No',
        STANDARD_PART: 'Standard part',
        STANDARD_PART_TRUE: 'Yes',
        START: 'Start',
        START_IMPORT: 'Start import',
        STATE_CHANGE: 'State change',
        STATUS: 'Status',
        STRUCTURE: 'Structure',
        SUB_PARTS: 'Assembly',
        SUM: 'Sum',
        SUBSCRIBE_ITERATION_CHANGE: 'Subscribe to iteration change notifications',
        SUBSCRIBE_STATE_CHANGE: 'Subscribe to document state change notifications',
        TAG: 'Tag',
        TAGS_HELP: 'Tags list, comma separated',
        TAGS: 'Tags',
        TAGS_TO_ADD: 'Tags to add',
        TAKE_SCREENSHOT: 'Take screenshot',
        TASK_APPROVED_ON: 'Task done on',
        TASK_CLOSED_ON: 'Task closed on',
        TASK_NAME_PLACEHOLDER: 'New task',
        TASK_REJECT_ON: 'Task reject on',
        TASK_WORKER: 'Processed by',
        TASKS_IN_PROGRESS: 'In progress',
        TASKS: 'Tasks',
        TEMPLATES: 'Templates',
        TEMPLATE: 'Template',
        TEXT: 'Text',
        LONG_TEXT: 'Long text',
        TITLE_HELP: 'Document title',
        TITLE: 'Title',
        TO: 'To',
        TOGGLE_ALL_LAYERS: 'Toggle all layers',
        TRACKBALL_MODE: 'Trackball mode',
        TRANSFORM_CONTROLS: 'Transformation',
        TRUE: 'True',
        TYPE: 'Type',
        UDF_DEF: 'Define function',
        UNCHECK_ALL: 'Uncheck all',
        UNDO_CHECKOUT: 'Cancel checkout',
        UNDO_CHECKOUT_QUESTION: 'Undo checkout?',
        UNFOLD_TASK: 'Edit task',
        UNREACHABLE: 'Cannot invite user, user is unreachable',
        UNSUBSCRIBE_ITERATION_CHANGE: 'Unsubscribe from iteration change notifications',
        UNSUBSCRIBE_STATE_CHANGE: 'Unsubscribe from document state change notifications',
        UNIT: 'each',
        UNEXPECTED_ERROR: 'An unexpected error happened, please try again or contact support',
        UPDATE_ACL_ERROR: 'An error occurred while updating acl',
        URL: 'URL',
        USE_ACL: 'Use ACL ?',
        USER_DEFINED_FUNCTION: 'User defined function',
        USER_MEDIA_FAILED: 'Cannot access to your video input. Is this a WebRTC capable browser?',
        USERS_CONNECTED: 'users connected',
        USERS: 'Users',
        VALIDATION_FAILED_FOR: 'Validation failed for ',
        _VALIDATION_PATTERN_DATE: '\\d{4}-\\d{2}-\\d{2}',
        _VALIDATION_PATTERN_NUMBER: '^-?\\d+(\\.\\d+)?(([eE]([-+])?)?\\d+)?$',
        _VALIDATION_PATTERN_TIME: '\\d{2}:\\d{2}',
        VALUE: 'Value',
        VALUES: 'Values',
        VERIFICATION_NOTE: 'Verification note',
        VERIFIED: 'Verified',
        VERSION: 'Version',
        VERSIONS: 'Versions',
        VIDEO_INVITATION_SENT: 'Invitation has been sent to remote user, waiting for him/her to accept',
        VIDEO_INVITE_ACCEPT: 'Accept',
        VIDEO_INVITE_NOTIFICATION_TITLE: 'Video invite',
        VIDEO_INVITE_REJECT: 'Reject',
        VIDEO_INVITE_TEXT: 'is inviting you to a video chat session',
        VIEW_MODE: 'View mode',
        VISUALIZE_ASSEMBLY: 'Visualize assembly',
        VISUALIZE_PRODUCT: 'Visualize product',
        WARNINGS: 'Warnings:',
        WAITING_REMOTE_VIDEO: 'Waiting for remote video.',
        WAITING_USER_MEDIA: 'Waiting user media ... Please accept the prompt from your browser.',
        USED_BY: 'Used by',
        WITHDRAW_INVITATION: 'Withdraw invitation',
        WITH_LINKS: 'With links',
        WITHOUT_LINKS: 'Without links',
        WORKFLOW_HISTORY: 'History',
        WORKFLOW_LEGEND_COMPLETE: 'Complete',
        WORKFLOW_LEGEND_INCOMPLETE: 'Incomplete',
        WORKFLOW_LEGEND_INPROGRESS: 'In progress',
        WORKFLOW_LEGEND_REJECTED: 'Rejected',
        WORKFLOW_NAME_PLACEHOLDER: 'Workflow name',
        WORKFLOW: 'Workflow',
        WORKFLOW_COPY: 'Workflow copy',
        WORKFLOWS: 'Workflows',
        WORKSPACES_ADMINISTRATION: 'Workspaces administration',
        WORKSPACE_MANAGEMENT: 'Workspace administration',
        WORKSPACES: 'Workspaces',
        WORKSPACE: 'Workspace',
        YOU_CANNOT_CREATE_LINK_WITHOUT_TYPE: 'You cannot create a link without a type',
        YOU_HAVE_BEEN_KICKED: 'You have been kicked from the collaborative room',
        LANGUAGES: {
            fr: 'French',
            en: 'English',
            ru: 'Russian'
        }
    }
});
