/*global define*/
define({
    ABOUT_DOCDOKUPLM: 'Информация о DocDokuPLM',
    ABSOLUTE: 'Абсолютно',
    ACCEPT_VIDEO_INVITE: 'Принять',
    ACCESS_RIGHTS: 'Приянть правила',
    ACL: 'ACL',
    ACTIVITY_STATE_PLACEHOLDER: 'Новое состояние',
    ADD_ACTIVITY: 'Добавить действие',
    ADD: 'Добваить',
    ADD_CALCULATION: 'Добавить вычисление',
    ADD_COMMENT: 'Добавить комментарий',
    ADD_DOCUMENT: 'Добавить документ',
    ADD_DOCUMENTS_TO_BASELINE: 'Добавить документ в постоянную коллекцию',
    ADD_ISSUE: 'Добавить проблему',
    ADD_NEW_TAG: 'Добавить новый тэг',
    ADD_NOTIFICATION: 'Добавить уведомление',
    ADD_PART: 'Добавить деталь',
    ADD_REQUEST: 'Добавить запрос',
    ADD_REVISION_NOTE: 'Добавить примечание',
    ADD_TASK: 'Добавить задачу',
    ADD_TEMPLATE_ATTRIBUTES: 'Добавить атрибут поставки',
    ADMINISTRATED: 'Администрировать',
    ADVANCED: 'Дополнительно',
    ADVANCED_SEARCH: 'Расширенный поиск',
    AFFECTED_ELEMENT: 'Затрагиваемый элемент',
    ALERT_ROLE_IN_USE: 'Эта роль не может быть удалена, потому что используется в каком-то потоке работ',
    ALL: 'Все',
    ALL_PRODUCTS: 'Все изделия',
    ALL_TASKS: 'Все задачи',
    AMOUNT: 'Количество',
    APPEND: 'Добавить',
    APPEND_LAYER: 'Создать новый слой',
    APPROVE_TASK: 'Пометить задачу как выполненная',
    ASSIGNED_ROLE_PRE_FILL: 'Назначение по умолчанию',
    ASSIGNED_ROLE_REQUIRED: 'Вы должны назначить хотя бы одного пользователя или группу',
    ASSIGNED_USERS: 'Назначенные пользователи',
    ASSIGNED_USERS_PRE_FILL: 'Предварительное заполнение пользователей по умолчанию',
    ASSIGNED_USERGROUPS: 'Назначенные группы',
    ASSIGNED_USERGROUPS_PRE_FILL: 'Предворительное заполнение групп по умолчанию',
    ASSIGNMENTS: 'Назначения',
    ATTACHED_FILES: 'Прикрепленные файлы',
    ATTRIBUTES: 'Атрибуты',
    AUTHOR: 'Автор',
    AUTHOR_LOGIN: 'Логин автора',
    AUTHOR_NAME: 'Имя автора',
    AUTHOR_DOCUMENT_HELP: 'Автор документа или пользователь работавший над этим документом',
    AUTHOR_PART_HELP: 'Автор детали или пользователь работавший над этим деталью',
    AUTO_CHECKIN: 'Автоматически регистрировать детали которые были разрегистрированы во время импорта',
    AUTO_CHECKOUT: 'Автоматически разрегистрировать если необходимо',
    AVG: 'Среднее',
    BACK: 'Назад',
    BASED_ON: 'Основывается на',
    BASELINE: 'Базовая линия',
    BASELINE_DELETION_ERROR: 'Нельзя удалить базовую линию : ',
    BASELINE_OF: 'Базовая линия',
    BASELINES: 'Базовые линии',
    BEST_FIT_VIEW: 'Наилучший вид',
    BLOCKER_TEXT: '(Z, Q, S, D = Перемещение, SPACE = Вверх, CTRL = Вниз, MOUSE = Повернуть вокруг, ESC = Выйти)',
    BLOCKER_TITLE: 'Нажмите чтобы запустить сцену',
    BOM_VIEW: 'Спецификация',
    BOOLEAN: 'Логический',
    BY: 'by',
    CAD_FILE: 'CAD файл',
    CAD_FILES: 'CAD файлы',
    CALCULATIONS: 'Расчеты',
    CALL_TO_TITLE: 'Обратиться к',
    CANCEL: 'Отмена',
    CANCEL_CHECKOUT: 'Отменить разрегистрацию',
    CANCEL_PART_CREATION: 'Отметить создание детали',
    CANNOT_CREATE_PC: 'Невозможно создать объект RTCPeerConnection, WebRTC не поддерживается этим браузером.',
    CANNOT_DELETE_FILE: 'Невозможно удалить файл : ',
    CHANGE_ITEM_ASSIGNEE: 'Назначение',
    CHANGE_ITEM_CATEGORY: 'Категория',
    CHANGE_ITEM_PRIORITY: 'Приоритет',
    CHANGES: 'Редактировать управление',
    CHANGE_MANAGEMENT: 'Редактировать управление',
    CHANNEL_NOT_READY_ERROR: 'Не удается установить связь с сервером вызовов. Пожалуйста, убедитесь, что ваш браузер поддерживает websocket, или ваш интернет-провайдер не блокирует их.',
    CHECK_ALL: 'Проверить все',
    CHECKED_IN: 'Загеристрировано',
    CHECKIN: 'Зарегистрировать',
    CHECKIN_DATE: 'Дата регистрации',
    CHECKOUT_BY: 'Разрегистрировал',
    CHECKOUT: 'Разрегистрировано',
    CHECKOUT_DATE: 'Дата разрегистрации',
    CHECKOUTS: 'Разрегистрировано',
    CHOICES: 'Выбор',
    CHOOSE_A_PRODUCT: 'Выбранный продук',
    CHOSEN_OPTIONALS: 'Исключенный опции',
    CHOSEN_SUBSTITUTES: 'Выбранные заменители',
    CLEAR: 'Очистить',
    CLIPPING: 'Обрезка',
    CLOSE: 'Закрыть',
    CLOSING_PEER_CON: 'Закрытие подключение ...',
    CLOSURE_COMMENT: 'Закрыть комментарий',
    COLLABORATIVE: 'Общий доступ',
    COLLABORATIVE_INVITE: 'Вас приглашают присоединиться к комнате',
    COLLABORATIVE_KICKED: 'Вы были выкинуты из комнаты',
    COLLABORATIVE_LEAD: 'Ведущий',
    COLLABORATIVE_NO_MASTER: 'Отсутствует',
    COLLABORATIVE_NOT_INVITED: 'Вы не приглашены в эту комнату',
    COLLABORATIVE_WITHDRAW_INVITATION: 'Приглашение отменено',
    COMMENT: 'Комментарий',
    COMPONENT_SELECTED: 'Выделенная деталь',
    CONFIG_SPEC: 'Конфигурировать спецификацию',
    CONFIGURATION: 'Конфигурация',
    CONFIGURATIONS: 'Конфигурации',
    CONFIRM: 'Подтвердить',
    CONFIRM_IMPORT: 'Подтвердить импорт?',
    CONFIRM_IMPORT_WITH_OPTION: 'Подтвердить импорт с опциями:',
    CONFIRM_PASSWORD: 'Подтвердить пароль',
    CONNECTED: 'Подключено',
    CONNECTING: 'Подключение...',
    CONTAINS_OBSOLETE_PARTS: 'Содержит устаревшие детали',
    CONTENT: 'Содержание',
    CONTENT_HELP: 'Содержание файла(ов)',
    CONTROLS_SHORTCUTS: 'Горяие клавишы мыши/клавиатуры',
    CONVERSION: 'Преобразование',
    CONVERSION_STATUS: 'Изменение статуса',
    CONVERSION_PENDING: 'Ожидание перехода',
    CONVERSION_SUCCEEDED: 'Переход успешный',
    CONVERSION_FAILED: 'Переход не удался',
    COPY: 'Копировать',
    COWORKERS: 'Сотрудники',
    CREATE: 'Создать',
    CREATE_BASELINE: 'Создать базовую линию',
    CREATE_DOCUMENT_COLLECTION: 'Создание коллекции документов',
    CREATE_NEW_EFFECTIVITY: 'Создать новую применяемость',
    CREATE_NEW_EFFECTIVITY_ERROR: 'Применяемость не создана',
    CREATE_NEW_EFFECTIVITY_SUCCESS: 'Применяемость создана',
    CREATE_NEW_PART: 'Создать новую деталь',
    CREATE_NEW_PART_AS_SUBSTITUTE: 'Создать новую деталь как замену',
    CREATE_NEW_VERSION: 'Создать новую версию',
    CREATE_PART: 'Создать деталь',
    CREATE_PART_SUBSTITUTE_TOOLTIP: 'Чтобы создать заменяющую ссылку, сначала необходимо выбрать для чего создается ссылка',
    CREATE_PART_TOOLTIP: 'Чтобы создать новую ссылку использования, не один из элементов не должен быть выбран',
    CREATE_PRODUCT: 'Создать изделие',
    CREATE_ROOM: 'Начать обзор цифрового макета',
    CREATION_DATE: 'Дата создания',
    CREATION_ERROR: 'Произошла ошибка во время создания',
    CURRENT_PASSWORD: 'текущий пароль',
    CURRENT_TAGS: 'Теги связанные с',
    CURRENT_WORKFLOW: 'Текущий поток работ',
    CUTPLAN: 'План разреза',
    DATE: 'Дата',
    _DATE_FORMAT: 'MM-DD-YYYY HH:mm:ss',
    _DATE_PICKER_DATE_FORMAT: 'YYYY-MM-DD',
    _DATE_SHORT_FORMAT: 'MM-DD-YYYY',
    DATE_SORT: 'date_sort',
    DBL_CLICK: 'Двойной клик',
    DELETE_ACTIVITY: 'Удалить действие',
    DELETE: 'Удалить',
    DELETE_FOLDER_QUESTION: 'Удалить папку?',
    DELETE_LINKED_ITEM: 'Удалить ссылку',
    DELETE_MARKER: 'Удалить маркер',
    DELETE_PRODUCT_CONFIRM: 'Вы действительно хотите удалить это изделие?',
    DELETE_PRODUCT: 'Удалить изелие',
    DELETE_PRODUCT_ERROR: 'Ошибка при удаление изделия',
    DELETE_SELECTION: 'Удалить выбранное',
    DELETE_SELECTION_QUESTION: 'Удалить выбранное',
    DELETE_TAG_QUESTION: 'Удалить выбранный тег?',
    DELETE_QUERY_QUESTION: 'Удалить выбранный запрос?',
    DELETE_TASK: 'Удалить задачу',
    DESCRIPTION: 'Описание',
    DEVICE_ERROR: 'Невозможно получить доступ к вашему аудио/видео устройству, пожалуйста, выберите браузер поддерживащий WebRTC, и если на этом веб-сайте нет исключения.',
    DISPLAY_COMMENTS: 'Скрыть/показать определение',
    DOCUMENT: 'Документ',
    DOCUMENT_REVISION_NOTE_PROMPT_LABEL: 'Вы хотите добавить примечание к документу без него?',
    DOCUMENT_S_DESCRIPTION: 'Описание документа',
    DOCUMENT_S_REFERENCE: 'ID документа',
    DOCUMENT_S_TITLE: 'Заголовок документа',
    DOCUMENT_TEMPLATES: 'Шаблон документа',
    DOCUMENT_TYPE_HELP: 'Тип документа',
    DOCUMENT_VERSION_HELP: 'Версия документа',
    DOCUMENTS: 'Документы',
    DOCUMENTS_CHOICE: 'Выбранные документы',
    DOCUMENTS_CHOICE_EXPLANATION: 'Выберите несколько документы из папки',
    DOCUMENT_COLLECTION: 'Колекция документов',
    DOCUMENT_COLLECTION_IN_PROGRESS: 'Колекция документов в процессе',
    DOCUMENT_COLLECTIONS: 'Колекции документов',
    DOCUMENT_MANAGEMENT: 'Управление документами',
    DOWNLOAD_DPLM_CLIENT: 'Скачать DPLM клиент',
    DOWNLOAD_ZIP: 'Скачать все файлы в ZIP',
    DROP_FILE_HERE: 'или удалить его здесь',
    DROP_FILES_HERE: 'или удалить их здесь',
    DUE_DATE: 'срок',
    DUPLICATE: 'Дубликат',
    DUPLICATE_WORKFLOW: 'Дублировать поток работ',
    EDIT_BASELINE: 'Редактировать базовую линию',
    EDIT: 'Редактировать',
    EDIT_ISSUE: 'Редактировать ошибку',
    EDIT_LINKED_DOCUMENTS: 'Редактировать ссылку',
    EDIT_MILESTONE: 'Редактировать веху',
    EDIT_ORDER: 'Редактировать заказ',
    EDIT_PRODUCT: 'Редактировать изделие',
    EDIT_PRODUCT_INSTANCE: 'Редактировать доставку',
    EDIT_REQUEST: 'Редактировать запрос',
    EDITION_ERROR: 'Произошла ошибка во время редактирования',
    EFFECTIVITY: 'Применяемость',
    EFFECTIVITY_DATE: 'Дата',
    EFFECTIVITY_DESCRIPTION: 'Описание',
    EFFECTIVITY_END_DATE: 'Дата окончания',
    EFFECTIVITY_END_LOT_ID: 'Конечная партия',
    EFFECTIVITY_END_NUMBER: 'Конец серийного номера',
    EFFECTIVITY_LOT: 'Базовая партия',
    EFFECTIVITY_NAME: 'Название',
    EFFECTIVITY_SERIAL_NUMBER: 'Базовый серийный номер',
    EFFECTIVITY_START_DATE: 'Дата начала',
    EFFECTIVITY_START_LOT_ID: 'Начальная партия',
    EFFECTIVITY_START_NUMBER: 'Начало серийного номера',
    EFFECTIVITY_TYPE: 'Тип применяемости',
    EMBED_SCENE: 'Вставить сцены',
    EMAIL: 'Email',
    EMPTY_CHOICES: 'Нельзя создать конфигурацию без выбранной детали',
    EMPTY_REVISION_NOTE: 'Пустое примечание. Пожалуйста, отключите опцию или напишите примечание',
    END: 'Конец',
    ENTER_NAV: 'Начать навигацию',
    ERROR: 'Ошибка',
    ERRORS: 'Ошибки:',
    ERROR_404: 'ERROR 404. Мы не смогли найти то, что вы ищете...',
    ERROR_404_SORRY: 'Извините !',
    EXISTING_TAGS: 'Доступные теги',
    EXIT: 'Закончить обзор цифрового макет',
    EXPIRE_DATE: 'Срок годности',
    EXPLODE: 'Развернуть',
    EXPORT: 'Экспорт',
    EVERYTHING: 'Все',
    FALSE: 'Ложь',
    FILE: 'Файл',
    FILE_DELETION_ERROR: 'Файл с %{id} не может быть удален',
    FILE_UPLOADED: 'Файл загружен',
    FILES_UPLOADED: 'Файлы загружены',
    FILES: 'Файлы',
    FILL: 'Заполнить',
    FILTER: 'Филтр',
    FINAL_STATE_PLACEHOLDER: 'Конечное состояние',
    FIRST_PAGE: 'Первая страница',
    FIT_VIEW: 'Подходящий вид',
    FLYING_MODE: 'Порящая модель',
    FLY_TO: 'Переместиться в',
    FOLDER: 'Папка',
    FOLDERS: 'Папки',
    FOLDER_S_NAME: 'Имя папки',
    FOLD_TASK: 'Минимизировать задачи',
    FORBIDDEN: 'Доступ запрещен',
    FORBIDDEN_MESSAGE: 'Вы не можете получить доступ к этому ресурсу, вам необходимо войти в систему',
    FORM_HELPER: 'Оставьте эти поля пустыми, если вы не хотите указывать пароль или дату истечения срока действия',
    FREEZE_CURRENT_ITERATION: 'Блокировать текущую итерацию',
    FREEZE_AFTER_MODIFICATION: 'Блокировать итерацию после изменения',
    FROM: 'Из',
    FULL_ACCESS: 'Полный доступ',
    FULL_SCREEN: 'Полный экран',
    GENERAL: 'Основной',
    GENERATED_URL: 'Сгенерированный URL',
    GIVE_HAND: 'Помочь',
    GO_TO_PAGE: 'Перейти к странице ...',
    GOTO_PARALLEL_MODE: 'Переключить действие в параллельный режим',
    GOTO_SEQUENTIAL_MODE: 'Переключить действие в последовательный режим',
    GRID_SWITCH: 'Показать/скрыть сетку',
    GROUPS: 'Группы',
    HAS_SUBSTITUTES: 'Имеет заменитель',
    HEAD_CHECKIN: 'Последняя регистрация',
    HEAD_RELEASED: 'Последний релиз',
    HEAD_WIP: 'В работе',
    HIDE_SUBSTITUTES: 'Скрыть заменитель',
    HOME_PAGE: 'Домой',
    HOURS: 'ч',
    HISTORY: 'История',
    ID_GENERATION: 'Id генератор',
    IGNORE: 'Игнорировать',
    IMPORT_ATTRIBUTE_FILE: 'Импорат атрибутов файла',
    IMPORT_DELIVERABLE_DATA: 'Импорт данных доставки',
    IMPORT_PART_DATA: 'Ипорт данных детали',
    IMPORTER: 'Импорт',
    IMPORT_PENDING: 'Идет импорт',
    IMPORT_SUCCEEDED: 'Успешно импортировано',
    IMPORT_FAILED: 'Импорт не удался',
    INIT_VALUE: 'Начальная значение',
    IN_PROGRESS: 'В работе',
    INITIATOR: 'Инициатор',
    INSTANCE_SELECTED: 'Выбран экземпляр',
    INSTRUCTIONS: 'Инструкции',
    INVERT_SOURCE_DESTINATION: 'Поменять местами отправление и назначение',
    INVITE: 'Пригласите колег',
    ISSUES: 'Ошибки',
    IS_COMPONENT_OF: 'Является компонентом :',
    IS_SUBSTITUTE_IN: 'Поставляется в :',
    IS_SUBSTITUTE: 'Замена',
    ITERATION_CHANGE: 'Изменение итерации',
    ITERATION: 'Итерация',
    KEYBOARD_SHORTCUTS: 'Горячие клавиши',
    KG: 'кг',
    LAST_ITERATION: 'Текущая итерация',
    LAST_PAGE: 'Последняя страница',
    LATEST: 'Последний(яя)',
    LATEST_SHORT: 'Последняя версия',
    LAYERS: 'Слои',
    LEAVE_NAV: 'Остановить навигацию',
    LEFT_CLICK: 'Левая клавиша мишы',
    LIFECYCLE_STATE: 'Состояние жизненного цикла',
    LINK_DESCRIPTION: 'Ссылка на описание',
    LINKED_DOCUMENTS: 'Ссылающиеся документы',
    LINKS: 'Ссылки',
    LOADING: 'Загрузка',
    LOCK_ATTRIBUTES: 'Зафиксировать структуру атрибутов',
    LOCKED: 'Заблокировано',
    LOGIN: 'Войти',
    LOGOUT: 'Выйти',
    LOOK_AT: 'Посмотреть на',
    MANAGE_PRODUCT: 'Управление изделиями',
    MANAGE_ROLES: 'Административные роли',
    MANDATORY: 'Обязательное',
    MARK_ALL_AS_VERIFIED: 'Отметить все как проверенные',
    MARK_AS_VERIFIED: 'Отметить как проверенно',
    MARK_AS_OBSOLETE: 'Отметить как устаревшее',
    MARK_DOCUMENT_AS_OBSOLETE_QUESTION: 'Отметить как устаревшее выделнный документ?',
    MARK_PART_AS_OBSOLETE_QUESTION: 'Отметить как устаревшее выделенную деталь?',
    MARKER_INFO: 'Получить информацию о маркерах',
    MARKERS: 'Маркеры',
    MARKERS_OPACITY: 'Изменить прозрачность маркеров',
    MARKERS_SIZE_MAX: 'Увеличить размер маркеров',
    MARKERS_SIZE_MIN: 'Уменьшить размер маркеров',
    MASK_HELP: 'Определите формат маски для ID документов/деталей, в которых будет подставляться этот шаблон. \n\nКроме того, для любых обычных символов вы можете использовать \'#\' для любого допустимого числа и \'*\' для любого символа. \n\nДля ID \'FAX-AZE-12\' можно использовать следующюю маску \'FAX-***-##\'.\n\n Маска с любым символом подстановочных знаков не может быть использована более одного раза.',
    MASK: 'Маска',
    MEASURE: 'Размер',
    METER: 'м',
    MILESTONE: 'Веха',
    MILESTONES: 'Вехи',
    MODIFICATION_DATE: 'Изменная дата',
    MODIFICATION_NOTIFICATION_LIST_DESCRIPTION: 'История изменений подсборок/деталей',
    MOUSE_CONTROLS: 'Управление мышью',
    MOVE: 'переместить',
    MOVE_BACKWARD: 'Назад',
    MOVE_DOWN: 'Вниз',
    MOVE_FORWARD: 'Вперед',
    MOVE_LEFT: 'Влево',
    MOVE_RIGHT: 'Вправо',
    MOVE_SCENE: 'Переместиться в сцену',
    MOVE_UP: 'Вверх',
    MULTIPLE_VERSIONS_FOR_DOCUMENT: 'Этот документ уже добавлен с другой версией',
    MY_ACCOUNT: 'Мой профиль',
    MY_ORGANIZATION: 'Моя организация',
    MY_WORKSPACES: 'Мое рабочее пространство',
    NAME: 'Имя',
    NAVIGATION: 'Навигация',
    NB_TASKS_TO_COMPLETE: 'Задача завершена',
    NEW_BASELINE: 'Новая базовая линия',
    NEW_CONFIGURATION: 'Новая конфигурация',
    NEW_DOCUMENT: 'Новый документ',
    NEW_DOCUMENT_COLLECTION: 'Новая колекция документа',
    NEW_EFFECTIVITY: 'Новая применяемость',
    NEW_FOLDER: 'Новая папка',
    NEW_ISSUE: 'Новая проблема',
    NEW_LAYER: 'Новый слой',
    NEW_LINK_TYPE: 'Создать новый тип ссылки',
    NEW_MARKER: 'Новый маркер',
    NEW_MILESTONE: 'Новая веха',
    NEW_ORDER: 'Новый заказ',
    NEW_PART: 'Новая деталь',
    NEW_PART_TEMPLATE: 'Новый шаблон детали',
    NEW_PASSWORD: 'Новый пароль',
    NEW_PRODUCT_INSTANCE: 'Новая доставка',
    NEW_PRODUCT: 'Новое изделие',
    NEW_REQUEST: 'Новый запрос',
    NEW_ROLE: 'Новая роль',
    NEW_TAG: 'Новый тег',
    NEW_TEMPLATE: 'Новый шаблон документа',
    NEW_UNIT: 'Новая единица',
    NEW_VERSION: 'новая версия',
    NEW_VERSION_OF: 'новая версия',
    NEW_WORKFLOW: 'Новый поток работ',
    NEXT_PAGE: 'Next Следующая страница',
    NO_CONVERSION: 'Нет изменений',
    NO_COWORKER: 'Нет колег',
    NO_DATA: 'Данные отсутствуют в таблице',
    NO_FILE_TO_IMPORT: 'Файл не импортирован',
    NO_FILTERED_DATA: 'Подходящих записей не найдено',
    NO_LAYERS: 'Нет слоев',
    NO_PARTICIPANT: 'Нет участников. Пригласите участника из меню Коллеги',
    NOTIFICATIONS: 'Уведомление',
    NOTHING_HERE: 'Ничего не найдно. Не верная ссылка...',
    NOT_INVITED_COLLABORATIVE_ROOM: 'У вас нет приглашения к этой комнате',
    NOT_VERIFIED: 'Не проверено',
    NO_WEBGL: 'Нет доступного или активного WebGL',
    NOT_YET_REGISTERED_QUESTION: 'Вы не зарегистрированы?',
    NOT_YET_REGISTERED_REGISTER: 'Зарегистрироваться!',
    NODE_ASSEMBLIES_VISITED: 'Посещаемые собрания',
    NODE_INSTANCES_VISITED: 'Посещаемые объекты',
    NONE: 'Ничего',
    NOTIFY_BY_TAG: 'Уведомить пользователя(ей) об изменениях помечаных тегом...',
    NUMBER: 'Число',
    LITER: 'л',
    LIST_LOV: 'Редактировать списки значений',
    LOCK: 'Заблокировать',
    LOV: 'Лист значений',
    OBSOLETE: 'Устаревший',
    OBSOLETE_AUTHOR: 'Устаревший автора',
    OBSOLETE_DATE: 'Устаревшая дата',
    OFFICIAL_SITE: 'Сообщество PLM',
    OFFLINE: 'Оффлайн',
    OK: 'OK',
    ON: 'нет',
    OR: 'или',
    ONLINE: 'Онлайн',
    OPEN_NEW_WINDOW: 'Открыть в новом окне',
    OPTIONAL: 'Опционально',
    OPTIONAL_REMOVE: 'None',
    OPTIONS: 'Опции',
    OR_ADD_PART: 'Или добавить сущствующую деталь',
    ORBIT_MODE: 'Режим Orbit',
    ORDERS_NUMBER: 'Число заказов',
    ORDERS: 'Заказы',
    OTHERS: 'Остальные',
    PATH_TO_PATH_LINKS: 'Типизированные ссылки',
    PARALLEL_ACTIVITY: 'Требуется паралельная ',
    PART_ATTRIBUTES: 'Атрибуты детали',
    PART_ATTRIBUTES_TEMPLATES: 'Шаблоны атрибутов детали',
    PARTICIPANT: 'Участники',
    PART_DESCRIPTION: 'Описание',
    PART_NAME: 'Название',
    PART_NOT_FOUND: 'Родительская деталь не найдена',
    PART_NUMBER_HELP: 'Номер детали',
    PART_NUMBER: 'Номер детали',
    PARTS: 'Детали',
    PART_REVISION_NOTE_PROMPT_LABEL: 'Добавить примечание к детали без нее?',
    PART_SEARCH_HELP: 'Текст',
    PART_SUBSTITUTE: 'Деталь аналог',
    PARTS_SUBSTITUTES: 'Детали аналоги',
    PART_TEMPLATE: 'Шаблон детали',
    PART_TEMPLATES: 'Шаблоны',
    PART_TYPE_HELP: 'Тип детали',
    PART_VERSION_HELP: 'Версия детали',
    PASSWORD: 'Пароль',
    PASSWORD_NOT_CONFIRMED: 'Введенные пароли должны совпадать',
    PATH: 'Папка',
    PATH_TO_PATH_SOURCE: 'Из этой папки',
    PATH_TO_PATH_TARGET: 'В эту папку',
    PATH_TO_PATH_SOURCE_LINK: 'Ссылка на исходную папку',
    PATH_TO_PATH_TARGET_LINK: 'Ссылка на целевую папку',
    PENDING: 'Отсутствующий участник',
    PERMALINK: 'Постоянная ссылка',
    PERMISSIVE_UPDATE: 'Обновление по разрешению',
    PERMISSIVE_UPDATE_PART: 'Обновление по разрешению (обновляются только изменные детали)',
    PERMISSIVE_UPDATE_PATH_DATA: 'Обновление по разрешению (обновляются только изменные данные о поставках)',
    POSSIBLE_VALUE: 'возможные значения',
    PREVIOUS_PAGE: 'Предыдущая страция',
    PRIVATE_SHARE_TITLE: 'Папка с ограниченным доступом',
    PRODUCT: 'Изделие',
    PRODUCT_ID: 'Id Изделия',
    PRODUCT_INSTANCE: 'Изделие для доставки',
    PRODUCT_INSTANCES: 'Изделия для доставки',
    PRODUCT_INSTANCE_DATA: 'Дата доставки изделия',
    PRODUCT_INSTANCE_DATA_ATTRIBUTES: 'Данные атрибутов для доставки изделия',
    PRODUCT_INSTANCE_DATA_ATTRIBUTES_TEMPLATES: 'Шаблон для данных атрибутов доставки изделия',
    PRODUCT_NAME: 'Название',
    PRODUCT_MANAGEMENT: 'Управление изделиями',
    PRODUCTS: 'Изделия',
    PRODUCT_STRUCTURE: 'Структура изделия',
    PROTECTED_RESOURCE: 'Этот ресурс защищен паролем',
    PUBLIC_ACCESS_TITLE: 'Отркытый доступ по постоянной ссылке',
    PUBLIC_SHARE: 'Папка с общим доступом',
    PUBLISH: 'Опубликовать',
    QUERY_EXPORT_EXCEL_LOADING: 'Экспорт...',
    QUERY_EXPORT_EXCEL: 'Экспорт из Excel',
    QUICK_SEARCH: 'Быстрый поиск',
    QUERY_STANDARD: 'Стандартный запрос',
    QUERY_BUILDER_CONDITION_AND: 'И',
    QUERY_BUILDER_CONDITION_OR: 'ИЛИ',
    QUERY_BUILDER_OPERATORS_EQUALS: 'равен',
    QUERY_BUILDER_OPERATORS_NOT_EQUALS: 'не равен',
    QUERY_BUILDER_OPERATORS_IN: 'содержится в',
    QUERY_BUILDER_OPERATORS_NOT_IN: 'не содержится в',
    QUERY_BUILDER_OPERATORS_LESS: 'меньше',
    QUERY_BUILDER_OPERATORS_LESS_OR_EQUAL: 'меньше или равно',
    QUERY_BUILDER_OPERATORS_GREATER: 'больше',
    QUERY_BUILDER_OPERATORS_GREATER_OR_EQUAL: 'больше или равно',
    QUERY_BUILDER_OPERATORS_BETWEEN: 'между',
    QUERY_BUILDER_OPERATORS_BEGIN_WITH: 'начинается с',
    QUERY_BUILDER_OPERATORS_NOT_BEGIN_WITH: 'не начинается с',
    QUERY_BUILDER_OPERATORS_CONTAINS: 'содержит',
    QUERY_BUILDER_OPERATORS_NOT_CONTAINS: 'не содержит',
    QUERY_BUILDER_OPERATORS_ENDS_WITH: 'оканчивается на',
    QUERY_BUILDER_OPERATORS_NOT_ENDS_WITH: 'не оканчивается на',
    QUERY_BUILDER_OPERATORS_IS_EMPTY: 'ПУСТОЕ',
    QUERY_BUILDER_OPERATORS_IS_NOT_EMPTY: 'НЕ ПУСТОЕ',
    QUERY_BUILDER_OPERATORS_IS_NULL: 'NULL',
    QUERY_BUILDER_OPERATORS_IS_NOT_NULL: 'не NULL',
    QUERY_BUILDER_ERRORS_NO_FILTER: 'Не выбран фильтр',
    QUERY_BUILDER_ERRORS_EMPTY_GROUP: 'Группа пустая',
    QUERY_BUILDER_ERRORS_RADIO_EMPTY: 'Не выбрано значение',
    QUERY_BUILDER_ERRORS_CHECKBOX_EMPTY: 'Не выбрано значение',
    QUERY_BUILDER_ERRORS_SELECT_EMPTY: 'Не выбрано значение',
    QUERY_BUILDER_ERRORS_STRING_EMPTY: 'Пустое значение',
    QUERY_BUILDER_ERRORS_STRING_EXCEED_MIN_LENGTH: 'Должен содержать не менее {0} символов',
    QUERY_BUILDER_ERRORS_STRING_EXCEED_MAX_LENGTH: 'Долже содержать более {0} символов',
    QUERY_BUILDER_ERRORS_STRING_INVALID_FORMAT: 'Неверный формат ({0})',
    QUERY_BUILDER_ERRORS_NUMBER_NAN: 'Не число',
    QUERY_BUILDER_ERRORS_NUMBER_NOT_INTEGER: 'Не целое число',
    QUERY_BUILDER_ERRORS_NUMBER_NOT_DOUBLE: 'Не дробное число',
    QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MIN: 'Должно быть больше чем {0}',
    QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MAX: 'Должно быть меньше чем{0}',
    QUERY_BUILDER_ERRORS_NUMBER_WRONG_STEP: 'Должно быть кратным {0}',
    QUERY_BUILDER_ERRORS_DATETIME_EMPTY: 'Пустое значение',
    QUERY_BUILDER_ERRORS_DATETIME_INVALID: 'Неверный формат даты ({0})',
    QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MIN: 'Должно быть после {0}',
    QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MAX: 'Должно быть перед {0}',
    QUERY_BUILDER_ERRORS_BOOLEAN_NOT_VALID: 'Не логическое',
    QUERY_BUILDER_ERRORS_OPERATOR_NOT_MULTIPLE: 'Оператор {0} не может принимать несколько значений',
    QUERY_GROUP_AUTHOR: 'Автор',
    QUERY_GROUP_PART_MASTER: 'Мастер деталь',
    QUERY_GROUP_PART_REVISION: 'Редакция детали',
    QUERY_GROUP_PRODUCT: 'Изделие',
    QUERY_GROUP_ATTRIBUTE_STRING: 'Строковый атрибут',
    QUERY_GROUP_ATTRIBUTE_LONG_STRING: 'Атрибут длинная строка',
    QUERY_GROUP_ATTRIBUTE_PART_NUMBER: 'Атрибут номер детали',
    QUERY_GROUP_ATTRIBUTE_LOV: 'Атрибут список значений',
    QUERY_GROUP_ATTRIBUTE_URL: 'Атрибут URL',
    QUERY_GROUP_ATTRIBUTE_NUMBER: 'Числовый атрибут',
    QUERY_GROUP_ATTRIBUTE_DATE: 'Атрибут дата',
    QUERY_GROUP_ATTRIBUTE_BOOLEAN: 'Логический атрибут',
    QUERY_GROUP_CONTEXT: 'Контекст',
    QUERY_GROUP_PATH_DATA_ATTRIBUTE: 'Атрибут доставки',
    QUERY_NAME: 'Имя запроса',
    QUERY_SEARCH: 'Построитель запросов',
    QUERY_SELECT: 'Выбрать',
    QUERY_CONTEXT: 'Конекст',
    QUERY_WHERE: 'Где',
    QUERY_WHERE_CONTEXT: 'Фильтр поставляемых данных',
    QUERY_ORDER_BY: 'Сортировать по',
    QUERY_GROUP_BY: 'Группировать по',
    QUERY_CLEAR: 'очистить',
    QUERY_REMOVE_SAVED_QUERY: 'Удалить из списка запросов',
    QUERY_CHOOSE_EXISTING_REQUEST: 'Или используйте существующий...',
    QUERY_CONTEXT_ERROR: 'Не удается найти изделия',
    QUERY_ATTRIBUTES_ERROR: 'Не удается получить список атрибутов',
    QUERY_FILTER_STATUS_WIP: 'В работе',
    QUERY_FILTER_STATUS_RELEASED: 'Выпущено',
    QUERY_FILTER_STATUS_OBSOLETE: 'Устарело',
    QUERY_DEPTH: 'Глубина',
    READ_ONLY: 'Только чтение',
    REBASE: 'Rebase',
    REBASE_AUTHOR: 'Rebase автора',
    REBASE_SUCCESS: 'Поставка была Rebase',
    REFERENCE_HELP: 'ID документа',
    REFERENCE: 'ID',
    REFRESH_TREE: 'Обновить дерево',
    REJECT_TASK: 'Отклонить задачу',
    REJECT_VIDEO_INVITE: 'Отклонить',
    RELATIVE: 'Относительный',
    RELAUNCH_ACTIVITY_SELECTOR: 'Перезапустить действие, если было отклонено',
    RELEASE_DATE: 'Дата релиза',
    RELEASED_BY: 'Опубликовано',
    RELEASED: 'Опубликовано',
    RELEASED_SHORT: 'Последняя версия релиза',
    RELEASE: 'Релиз',
    RELEASE_NOW: 'Опубликовать сейчас',
    RELEASE_SELECTION_QUESTION: 'Опубликовать выделенное?',
    RELOAD: 'Перезагузить',
    REMOTE_ACCEPT: 'Удаленный пользователь принял вызов. Ожидание подключения ...',
    REMOTE_BUSY: 'Удаленный пользователь занят. Соединение прервано ...',
    REMOTE_HANGUP: 'Удаленный пользователь положил трубку',
    REMOTE_OFFLINE: 'Удаленный пользователь оффлайн. Вызов закончен ...',
    REMOTE_REJECT: 'Удаленный пользователь отклонил звонок. Вызов закончен ...',
    REMOTE_STREAM_ADDED: 'Добавлен удаленный поток',
    REMOTE_STREAM_REMOVED: 'Удаленный поток удален',
    REMOTE_TIMEOUT: 'Удаленный пользователь не ответил вовремя. Вызов прерван ...',
    REMOVE_DOCUMENT_FROM_COLLECTION: 'Удалить документ из колекции',
    RENAME: 'Переименовать',
    RENAME_WORKFLOW_COPY: 'Название копии',
    REPLACE: 'Сбросить',
    REQUESTS_NUMBER: 'Номер запроса',
    REQUESTS: 'Запросы',
    REQUIRED_FIELD: 'Пожалуйста, заполните поле',
    RESET: 'Сбросить',
    RESET_CAMERA: 'Сбросить камеру',
    RESULT: 'Результат',
    RETAIN: 'Сохранить',
    RETRY: 'Повторить попытку',
    REVISION_DATE: 'Дата редакции',
    REVISION_NOTE: 'Примечание к редакции',
    REVISION_NOTE_PROMPT_CANCEL: 'Игнорировать',
    REVISION_NOTE_PROMPT_LABEL: 'Вы хотите добавить примечание к редакции?',
    REVISION_NOTE_PROMPT_OK: 'Добавить примечание к редакции',
    RIGHT_CLICK: 'Правый клик',
    ROLE_NAME: 'Имя роли',
    ROLE: 'Роль',
    ROLES: 'Роли',
    ROOT_PART: 'Корневая деталь',
    ROTATE: 'Вращать',
    ROTATE_SCENE: 'Повернуть сцену',
    RUN: 'Запустить',
    SAVED: 'Сохранено',
    SAVE: 'Сохранить',
    SCALE: 'Масштаб',
    SCENE_VIEW: 'Вид сцены',
    SCROLL_DOWN: 'вниз',
    SCROLL_UP: 'вверх',
    SEARCH_OPTIONS: 'Параметры поиска по номеру или имени',
    SEARCH_PART_BEGINNING: 'Поиск детали начиная с ',
    SEARCH_PART_CALLED: 'Поиск детали отменен',
    SEARCH_PART_ENDING: 'Поиск детали заканчивается на ',
    SEARCH_PARTS: 'Поиск деталей',
    SEARCH: 'Поиск',
    SEARCHING: 'Идет поиск...',
    SEARCHING_FOR_PARTS: 'Идет поиск детлей, пожалуйста не закрывайте окно...',
    SECONDS: 'сек',
    SEE_IN_DOCUMENT_MANAGEMENT: 'Смотреть документ в модуле управления документами',
    SEE_IN_PRODUCT_MANAGEMENT: 'Смотреть деталь в модуле управления изделиями',
    SELECT_FILE: 'Выберите деталь',
    SELECT_FILES: 'Выберите один или несколько файлов',
    SEND: 'Отправить',
    SEQUENTIAL_ACTIVITY: 'В последовательном',
    SERIAL_NUMBER: 'Серийный номер',
    SESSION_CONNECTING: 'Подключение к сессии',
    SESSION_OPENED: 'Сессия открыта',
    SERVER_NOT_AVAILABLE: 'Сервер недоступен повторите попытку',
    SHARED_DOCUMENTS_TITLE: 'Общий доступ к документу',
    SHARED_PARTS_TITLE: 'Общий доступ к детале',
    SHARE: 'Общий доступ',
    SHORTCUTS_TITLE: 'Горячие клавиши',
    SHOW_ALL: 'Показать все',
    SHOW_BY_PAGE: 'Показывать по страницам',
    SHOW_EDITED_MESHES: 'Выделите отредактированные сетки',
    SHOW_SUBSTITUTES: 'Показать замены',
    SIGN_TASK: 'Подписать',
    SINGLE_FILE_RESTRICTION: 'Допускается только один файл',
    SORRY: 'Извините',
    SPACE: 'пробел',
    SQUARE_METER: 'м²',
    STANDARD_PART_ALL: 'Все',
    STANDARD_PART_FALSE: 'Нет',
    STANDARD_PART: 'Стандартная деталь',
    STANDARD_PART_TRUE: 'Да',
    START: 'Начало',
    START_IMPORT: 'Начало импорта',
    STATE_CHANGE: 'Изменение состояния',
    STATUS: 'Статус',
    STRUCTURE: 'Структура',
    SUB_PARTS: 'Сборка',
    SUM: 'Сумма',
    SUBSCRIBE_ITERATION_CHANGE: 'Подпишитесь на уведомления об изменении итерации',
    SUBSCRIBE_STATE_CHANGE: 'Подпишитесь на уведомления об изменении состояния документа',
    TAG: 'Тег',
    TAGS_HELP: 'Список тегов, разделенные запятыми',
    TAGS: 'Теги',
    TAGS_TO_ADD: 'Теги для добавления',
    TAKE_SCREENSHOT: 'Сделать снимок экрана',
    TASK_APPROVED_ON: 'Задача выполнена',
    TASK_CLOSED_ON: 'Закрыть задачу',
    TASK_NAME_PLACEHOLDER: 'Новая задача',
    TASK_REJECT_ON: 'Отклонить задачу',
    TASK_WORKER: 'Обработано',
    TASKS_IN_PROGRESS: 'В работе',
    TASKS: 'Задачи',
    TEMPLATES: 'Шаблоны',
    TEMPLATE: 'Шаблон',
    TEXT: 'Текст',
    LONG_TEXT: 'Длинный текст',
    TITLE_HELP: 'Заголовок документа',
    TITLE: 'Заголовок',
    TO: 'к',
    TOGGLE_ALL_LAYERS: 'Переключить все слои',
    TRACKBALL_MODE: 'Режим трекбола',
    TRANSFORM_CONTROLS: 'Трансформация',
    TRUE: 'Истина',
    TYPE: 'Тип',
    UDF_DEF: 'Определение функции',
    UNCHECK_ALL: 'Разрегистрировать все',
    UNDO_CHECKOUT: 'Отменить разрегистрацию',
    UNDO_CHECKOUT_QUESTION: 'Отменить разрегистрацию?',
    UNFOLD_TASK: 'Редактировать задачу',
    UNREACHABLE: 'Невозможно пригласить пользователя, пользователь недоступен',
    UNSUBSCRIBE_ITERATION_CHANGE: 'Отменить подписку на уведомления об изменения итерации',
    UNSUBSCRIBE_STATE_CHANGE: 'Отменить подписку на изменение состояния документа',
    UNIT: 'каждый',
    UNEXPECTED_ERROR: 'Произошла непредвиденная ошибка, повторите попытку или обратитесь в поддержку',
    UPDATE_ACL_ERROR: 'Произошла ошибка при обновлении acl',
    URL: 'URL',
    USE_ACL: 'Использовать ACL ?',
    USER_DEFINED_FUNCTION: 'Пользовательская функция',
    USER_MEDIA_FAILED: 'Невозможно получить доступ к вашему видеовходу. Ваш браузер, поддерживает WebRTC?',
    USERS_CONNECTED: 'пользователи подключены',
    USERS: 'Пользователи',
    VALIDATION_FAILED_FOR: 'Неудалось выполнить проверку ',
    _VALIDATION_PATTERN_DATE: '\\d{4}-\\d{2}-\\d{2}',
    _VALIDATION_PATTERN_NUMBER: '^-?\\d+(\\.\\d+)?(([eE]([-+])?)?\\d+)?$',
    _VALIDATION_PATTERN_TIME: '\\d{2}:\\d{2}',
    VALUE: 'Значение',
    VALUES: 'Значения',
    VERIFICATION_NOTE: 'Проверить примечание',
    VERIFIED: 'Проверено',
    VERSION: 'Версия',
    VERSIONS: 'Версии',
    VIDEO_INVITATION_SENT: 'Приглашение отправлено пользователю, ожидайте подтверждения',
    VIDEO_INVITE_ACCEPT: 'Принять',
    VIDEO_INVITE_NOTIFICATION_TITLE: 'Приглашение на видео',
    VIDEO_INVITE_REJECT: 'Отклонить',
    VIDEO_INVITE_TEXT: 'приглашает вас принять приглашение к видеочату',
    VIEW_MODE: 'Режим просмотра',
    VISUALIZE_ASSEMBLY: 'Визуализировать сборку',
    VISUALIZE_PRODUCT: 'Визуализировать изделие',
    WARNINGS: 'Предупреждение:',
    WAITING_REMOTE_VIDEO: 'Ожидание удаленного видео',
    WAITING_USER_MEDIA: 'Ожидание пользовательских данных ... Примите приглашение в своем браузере.',
    USED_BY: 'Использован',
    WITHDRAW_INVITATION: 'Отменить приглашение',
    WITH_LINKS: 'С ссылками',
    WITHOUT_LINKS: 'Без ссылок',
    WORKFLOW_HISTORY: 'История',
    WORKFLOW_LEGEND_COMPLETE: 'Завершено',
    WORKFLOW_LEGEND_INCOMPLETE: 'Незавершено',
    WORKFLOW_LEGEND_INPROGRESS: 'В работе',
    WORKFLOW_LEGEND_REJECTED: 'Отклонено',
    WORKFLOW_NAME_PLACEHOLDER: 'Название потока работ',
    WORKFLOW: 'Поток работ',
    WORKFLOW_COPY: 'Копировать поток работе',
    WORKFLOWS: 'Потоки работ',
    WORKSPACES_ADMINISTRATION: 'Администрирование рабочих мест',
    WORKSPACE_MANAGEMENT: 'Администрирование рабочего места',
    WORKSPACES: 'Рабочие места',
    WORKSPACE: 'Рабочее место',
    YOU_CANNOT_CREATE_LINK_WITHOUT_TYPE: 'Вы не можете создать ссылку без типа',
    YOU_HAVE_BEEN_KICKED: 'Вы были исключены из общей комнаты',
    LANGUAGES: {
        fr: 'French',
        en: 'English',
        ru: 'Russian'
    }
});
