/*global casper,homeUrl,login,pass,workspace*/
casper.test.begin('Workspace creation suite', 2, function workspaceTestsSuite() {

    'use strict';

    casper.clear();

    /**
     * Open workspace home page
     */
    casper.open(urls.workspaceAdministration);

    /**
     * Create the workspace
     */
    casper.then(function createNewWorkspace() {
        return this.waitForSelector('#workspace-management-menu a.new-workspace', function () {
            this.click('#workspace-management-menu a.new-workspace');
        }, function () {
            this.capture('screenshot/workspace/createNewWorkspace-error.png');
            this.test.assert(true, 'Workspace creation form should be displayed');
        });
    });

    /**
     * Fill the form
     */
    casper.then(function submitWorkspaceCreationForm() {
        return this.waitForSelector('#workspace-id', function () {
            this.sendKeys('#workspace-id', workspace);
            this.sendKeys('#description', "Generated by casperjs " + (new Date()).toLocaleDateString());
            this.click('#workspace_creation_form > div.actions-btn > div > input.btn-primary');
        }, function () {
            this.capture('screenshot/workspace/submitWorkspaceCreationForm-error.png');
            this.test.assert(true, 'Workspace creation form should be displayed');
        });
    });

    /**
     * Wait for workspaces list redirect
     * Assert workspace has been created
     */
    casper.then(function waitForRedirect() {
        return this.waitUntilVisible('.home-workspace-list-container', function () {
            this.test.assert(true, 'Redirected on workspaces list');
            var workspaceExists = this.evaluate(function (w) {
                return $('div.home-workspace-list-container.administrated-workspaces > div > div > h4:contains(' + w + ')').length === 1;
            }, workspace);
            this.test.assert(workspaceExists, 'Workspace exists');
        });
    });

    casper.run(function allDone() {
        return this.test.done();
    });

});
